{:start-coordinate-1-doc-values {:type "double", :doc_values true},
 :cloud-cover {:type "float", :store true},
 :crid-id-lowercase {:type "keyword"},
 :end-coordinate-1 {:type "double"},
 :mbr-crosses-antimeridian {:type "boolean"},
 :granule-ur {:type "keyword", :store true},
 :revision-id {:type "integer", :store true},
 :orbit-end-clat-doc-values {:type "double", :doc_values true},
 :end-direction {:type "keyword", :store true},
 :sensor-sn-lowercase {:type "keyword"},
 :cycle {:type "integer", :doc_values true},
 :instrument-sn-lowercase-doc-values {:type "keyword",
                                      :doc_values true},
 :lr-south {:type "float"},
 :mbr-south-doc-values {:type "float", :doc_values true},
 :start-date-doc-values {:type "date", :store true, :doc_values true},
 :native-id-lowercase {:type "keyword", :doc_values true},
 :concept-seq-id {:type "integer"},
 :orbit-start-clat-doc-values {:type "double", :doc_values true},
 :ords-info {:type "integer", :store true, :index false},
 :ords {:type "integer", :store true, :index false},
 :provider-id {:type "keyword", :store true},
 :readable-granule-name-sort2 {:type "keyword", :doc_values true},
 :mbr-north-doc-values {:type "float", :doc_values true},
 :provider-id-lowercase-doc-values {:type "keyword", :doc_values true},
 :platform-sn-lowercase {:type "keyword"},
 :end-date {:type "date", :store true},
 :end-coordinate-2 {:type "double"},
 :size-doc-values {:type "float", :store true, :doc_values true},
 :collection-concept-id-doc-values {:type "keyword",
                                    :store true,
                                    :doc_values true},
 :lr-north-doc-values {:type "float", :doc_values true},
 :temporals {:properties {:start-date {:type "date"},
                          :end-date {:type "date"}},
             :type "nested",
             :dynamic "strict"},
 :short-name-lowercase {:type "keyword"},
 :collection-concept-id {:type "keyword", :store true},
 :version-id-lowercase-doc-values {:type "keyword", :doc_values true},
 :instrument-sn {:type "keyword"},
 :entry-title-lowercase-doc-values {:type "keyword", :doc_values true},
 :sensor-sn-lowercase-doc-values {:type "keyword", :doc_values true},
 :update-time {:type "keyword", :store true, :index false},
 :collection-concept-seq-id-doc-values {:type "integer",
                                        :doc_values true},
 :project-refs-lowercase {:type "keyword"},
 :downloadable {:type "boolean", :store true},
 :native-id-stored {:type "keyword", :store true, :doc_values true},
 :atom-links {:type "keyword", :store true, :index false},
 :two-d-coord-name-lowercase {:type "keyword"},
 :start-coordinate-1 {:type "double"},
 :production-date {:type "date", :doc_values true},
 :entry-title-lowercase {:type "keyword"},
 :producer-gran-id-lowercase2 {:type "keyword", :doc_values true},
 :orbit-asc-crossing-lon {:type "double", :store true},
 :mbr-south {:type "float"},
 :feature-id {:type "keyword"},
 :size-double-doc-values {:type "double",
                          :store true,
                          :doc_values true},
 :metadata-format {:type "keyword", :store true, :index false},
 :orbit-calculated-spatial-domains {:properties {:orbital-model-name {:type "keyword"},
                                                 :orbit-number {:type "integer"},
                                                 :start-orbit-number {:type "double"},
                                                 :stop-orbit-number {:type "double"},
                                                 :equator-crossing-longitude {:type "double"},
                                                 :equator-crossing-date-time {:type "date"}},
                                    :type "nested",
                                    :dynamic "strict"},
 :start-coordinate-2 {:type "double"},
 :platform-sn-lowercase-doc-values {:type "keyword", :doc_values true},
 :version-id-lowercase {:type "keyword"},
 :producer-gran-id {:type "keyword", :store true},
 :mbr-north {:type "float"},
 :lr-east {:type "float"},
 :passes {:properties {:pass {:type "integer", :doc_values true},
                       :tiles {:type "keyword", :doc_values true}},
          :type "nested",
          :dynamic "strict"},
 :lr-west {:type "float"},
 :provider-id-lowercase {:type "keyword"},
 :size {:type "float", :store true},
 :orbit-end-clat {:type "double"},
 :granule-ur-lowercase2 {:type "keyword", :doc_values true},
 :project-refs {:type "keyword"},
 :mbr-east-doc-values {:type "float", :doc_values true},
 :lr-east-doc-values {:type "float", :doc_values true},
 :orbit-calculated-spatial-domains-json {:type "keyword",
                                         :store true,
                                         :index false},
 :end-date-doc-values {:type "date", :store true, :doc_values true},
 :collection-concept-seq-id {:type "integer"},
 :start-lat {:type "double", :store true},
 :sensor-sn {:type "keyword"},
 :provider-id-doc-values {:type "keyword",
                          :store true,
                          :doc_values true},
 :mbr-east {:type "float"},
 :lr-crosses-antimeridian {:type "boolean"},
 :end-coordinate-2-doc-values {:type "double", :doc_values true},
 :end-coordinate-1-doc-values {:type "double", :doc_values true},
 :platform-sn {:type "keyword"},
 :concept-seq-id-doc-values {:type "integer", :doc_values true},
 :short-name-lowercase-doc-values {:type "keyword", :doc_values true},
 :orbit-start-clat {:type "double"},
 :native-id {:type "keyword", :doc_values true},
 :access-value-doc-values {:type "float",
                           :store true,
                           :doc_values true},
 :revision-date-stored-doc-values {:type "date",
                                   :store true,
                                   :doc_values true},
 :browsable {:type "boolean", :store true},
 :day-night {:type "keyword", :store true},
 :day-night-lowercase {:type "keyword"},
 :orbit-asc-crossing-lon-doc-values {:type "double",
                                     :store true,
                                     :doc_values true},
 :coordinate-system {:type "keyword", :store true, :index false},
 :mbr-west-doc-values {:type "float", :doc_values true},
 :project-refs-lowercase-doc-values {:type "keyword",
                                     :doc_values true},
 :feature-id-lowercase {:type "keyword"},
 :mbr-west {:type "float"},
 :start-coordinate-2-doc-values {:type "double", :doc_values true},
 :start-date {:type "date", :store true},
 :concept-id {:type "keyword", :store true},
 :attributes {:properties {:time-value {:type "date"},
                           :float-value {:type "double"},
                           :datetime-value {:type "date"},
                           :group {:type "keyword"},
                           :int-value {:type "integer"},
                           :name {:type "keyword"},
                           :date-value {:type "date"},
                           :string-value {:type "keyword"},
                           :group-lowercase {:type "keyword"},
                           :string-value-lowercase {:type "keyword"}},
              :type "nested",
              :dynamic "strict"},
 :instrument-sn-lowercase {:type "keyword"},
 :created-at {:type "date", :doc_values true},
 :lr-north {:type "float"},
 :entry-title {:type "keyword", :store true, :index false},
 :day-night-doc-values {:type "keyword",
                        :store true,
                        :doc_values true},
 :revision-date {:type "date"},
 :lr-south-doc-values {:type "float", :doc_values true},
 :start-direction {:type "keyword", :store true},
 :two-d-coord-name {:type "keyword"},
 :cloud-cover-doc-values {:type "float",
                          :store true,
                          :doc_values true},
 :revision-date-doc-values {:type "date", :doc_values true},
 :access-value {:type "float", :store true},
 :crid-id {:type "keyword"},
 :end-lat {:type "double", :store true},
 :lr-west-doc-values {:type "float", :doc_values true}}
