;; WARNING: This file was generated from umm-cmn-json-schema.json. Do not manually modify.
(ns cmr.umm-spec.models.umm-common-models
   "Defines UMM Common clojure records."
 (:require [cmr.common.dev.record-pretty-printer :as record-pretty-printer]))

;; Describes the relevant platforms used to acquire the data in the collection. The controlled
;; vocabularies for platform types and names are maintained in the Keyword Management System (KMS).
(defrecord PlatformType
  [
   ;; The most relevant platform type.
   Type

   ShortName

   LongName

   ;; Platform-specific characteristics, e.g., Equator Crossing Time, Inclination Angle, Orbital
   ;; Period. The characteristic names must be unique on this platform; however the names do not
   ;; have to be unique across platforms.
   Characteristics

   Instruments
  ])
(record-pretty-printer/enable-record-pretty-printing PlatformType)

;; Information describing the scientific endeavor(s) with which the collection is associated.
;; Scientific endeavors include campaigns, projects, interdisciplinary science investigations,
;; missions, field experiments, etc. The controlled vocabularies for project names are maintained in
;; the Keyword Management System (KMS)
(defrecord ProjectType
  [
   ;; The unique identifier by which a project or campaign/experiment is known. The campaign/project
   ;; is the scientific endeavor associated with the acquisition of the collection. Collections may
   ;; be associated with multiple campaigns.
   ShortName

   ;; The expanded name of the campaign/experiment (e.g. Global climate observing system).
   LongName

   ;; The name of the campaign/experiment (e.g. Global climate observing system).
   Campaigns

   ;; The starting date of the campaign.
   StartDate

   ;; The ending data of the campaign.
   EndDate
  ])
(record-pretty-printer/enable-record-pretty-printing ProjectType)

;; Information about the device used to measure or record data in this collection, including direct
;; human observation. In cases where instruments have a single child instrument or the instrument
;; and child instrument are used synonymously (e.g. AVHRR), both Instrument and ComposedOf should be
;; recorded. The child instrument information is represented in a separate section. The controlled
;; vocabulary for instrument names is maintained in the Keyword Management System (KMS).
(defrecord InstrumentType
  [
   ShortName

   LongName

   ;; Instrument-specific characteristics, e.g., Wavelength, SwathWidth, Field of View. The
   ;; characteristic names must be unique on this instrument; however the names do not have to be
   ;; unique across instruments.
   Characteristics

   ;; The expanded name of the primary sensory instrument. (e.g. Advanced Spaceborne Thermal
   ;; Emission and Reflective Radiometer, Clouds and the Earth's Radiant Energy System, Human
   ;; Observation).
   Technique

   ;; Number of instruments used on the instrument when acquiring the granule data.
   NumberOfInstruments

   ComposedOf

   ;; The operation mode applied on the instrument when acquiring the granule data.
   OperationalModes
  ])
(record-pretty-printer/enable-record-pretty-printing InstrumentType)

;; Child object on an instrument. Has all the same fields as instrument, minus the list of child
;; instruments.
(defrecord InstrumentChildType
  [
   ShortName

   LongName

   ;; Instrument-specific characteristics, e.g., Wavelength, SwathWidth, Field of View. The
   ;; characteristic names must be unique on this instrument; however the names do not have to be
   ;; unique across instruments.
   Characteristics

   ;; The expanded name of the primary sensory instrument. (e.g. Advanced Spaceborne Thermal
   ;; Emission and Reflective Radiometer, Clouds and the Earth's Radiant Energy System, Human
   ;; Observation).
   Technique
  ])
(record-pretty-printer/enable-record-pretty-printing InstrumentChildType)

;; Defines the contact information of a data center or data contact.
(defrecord ContactInformationType
  [
   ;; A URL associated with the contact, e.g., the home page for the DAAC which is responsible for
   ;; the collection.
   RelatedUrls

   ;; Time period when the contact answers questions or provides services.
   ServiceHours

   ;; Supplemental instructions on how or when to contact the responsible party.
   ContactInstruction

   ;; Mechanisms of contacting.
   ContactMechanisms

   ;; Contact addresses.
   Addresses
  ])
(record-pretty-printer/enable-record-pretty-printing ContactInformationType)

(defrecord ContactGroupType
  [
   ;; This is the roles of the data contact.
   Roles

   ;; Uuid of the data contact.
   Uuid

   ;; This is the contact person or group that is not affiliated with the data centers.
   NonDataCenterAffiliation

   ;; This is the contact information of the data contact.
   ContactInformation

   ;; This is the contact group name.
   GroupName
  ])
(record-pretty-printer/enable-record-pretty-printing ContactGroupType)

;; Defines a data center which is either an organization or institution responsible for
;; distributing, archiving, or processing the data, etc.
(defrecord DataCenterType
  [
   ;; This is the roles of the data center.
   Roles

   ;; This is the short name of the data center. The controlled vocabulary for data center short
   ;; names is maintained in the Keyword Management System (KMS).
   ShortName

   ;; This is the long name of the data center.
   LongName

   ;; Uuid of the data center.
   Uuid

   ;; This is the contact groups of the data center.
   ContactGroups

   ;; This is the contact persons of the data center.
   ContactPersons

   ;; This is the contact information of the data center.
   ContactInformation
  ])
(record-pretty-printer/enable-record-pretty-printing DataCenterType)

;; Building block text fields used to construct the recommended language for citing the collection
;; in professional scientific literature. The citation language constructed from these fields
;; references the collection itself, and is not designed for listing bibliographic references of
;; scientific research articles arising from search results. A list of references related to the
;; research results should be in the Publication Reference element.
(defrecord ResourceCitationType
  [
   ;; The name of the data series, or aggregate data of which the data is a part.
   SeriesName

   ;; The name of the organization(s) or individual(s) with primary intellectual responsibility for
   ;; the collection's development.
   Creator

   ;; The name of the city (and state or province and country if needed) where the collection was
   ;; made available for release.
   ReleasePlace

   ;; The title of the collection; this is the same as the collection Entry Title.
   Title

   ;; The URL of the landing page for the collection.
   OnlineResource

   ;; The name of the individual or organization that made the collection available for release.
   Publisher

   ;; The date when the collection was made available for release.
   ReleaseDate

   ;; The volume or issue number of the publication (if applicable).
   IssueIdentification

   ;; The individual(s) responsible for changing the data in the collection.
   Editor

   ;; The mode in which the data are represented, e.g. atlas, image, profile, text, etc.
   DataPresentationForm

   ;; The version of the collection.
   Version

   ;; Additional free-text citation information.
   OtherCitationDetails
  ])
(record-pretty-printer/enable-record-pretty-printing ResourceCitationType)

(defrecord DoiType
  [
   ;; This element stores the DOI (Digital Object Identifier) that identifies the collection. Note:
   ;; The values should start with the directory indicator which in ESDIS' case is 10. If the DOI
   ;; was registered through ESDIS, the beginning of the string should be 10.5067. The DOI URL is
   ;; not stored here; it should be stored as a RelatedURL.
   DOI

   ;; The DOI organization that is responsible for creating the DOI is described in the Authority
   ;; element. For ESDIS records the value of https://doi.org/ should be used.
   Authority

   ;; This element stores the fact that a DOI (Digital Object Identifier) is not applicable or is
   ;; unknown for this record.
   MissingReason

   ;; This element describes the reason the DOI is not applicable or unknown.
   Explanation
  ])
(record-pretty-printer/enable-record-pretty-printing DoiType)

;; Stores the start and end date/time of a collection.
(defrecord RangeDateTimeType
  [
   ;; The time when the temporal coverage period being described began.
   BeginningDateTime

   ;; The time when the temporal coverage period being described ended.
   EndingDateTime
  ])
(record-pretty-printer/enable-record-pretty-printing RangeDateTimeType)

;; Method for contacting the data contact. A contact can be available via phone, email, Facebook, or
;; Twitter.
(defrecord ContactMechanismType
  [
   ;; This is the method type for contacting the responsible party - phone, email, Facebook, or
   ;; Twitter.
   Type

   ;; This is the contact phone number, email address, Facebook address, or Twitter handle
   ;; associated with the contact method.
   Value
  ])
(record-pretty-printer/enable-record-pretty-printing ContactMechanismType)

;; Enables specification of Earth science keywords related to the collection. The controlled
;; vocabulary for Science Keywords is maintained in the Keyword Management System (KMS).
(defrecord ScienceKeywordType
  [
   Category

   Topic

   Term

   VariableLevel1

   VariableLevel2

   VariableLevel3

   DetailedVariable
  ])
(record-pretty-printer/enable-record-pretty-printing ScienceKeywordType)

;; Additional unique attributes of the collection, beyond those defined in the UMM model, which the
;; data provider deems useful for end-user understanding of the data in the collection. Additional
;; attributes are also called Product Specific Attributes (PSAs) or non-core attributes. Examples
;; are HORIZONTALTILENUMBER, VERTICALTILENUMBER.
(defrecord AdditionalAttributeType
  [
   ;; Identifies a namespace for the additional attribute name.
   Group

   ;; The standard unit of measurement for the additional attribute. For example, meters, hertz.
   ParameterUnitsOfMeasure

   ;; An estimate of the accuracy of the values of the additional attribute. For example, for AVHRR:
   ;; Measurement error or precision-measurement error or precision of a data product parameter.
   ;; This can be specified in percent or the unit with which the parameter is measured.
   ParameterValueAccuracy

   ;; The smallest unit increment to which the additional attribute value is measured.
   MeasurementResolution

   ;; The minimum value of the additional attribute over the whole collection.
   ParameterRangeBegin

   ;; Describes the method used for determining the parameter value accuracy that is given for this
   ;; additional attribute.
   ValueAccuracyExplanation

   ;; Value of the additional attribute if it is the same for all granules across the collection. If
   ;; the value of the additional attribute may differ by granule, leave this collection-level value
   ;; blank.
   Value

   ;; The name (1 word description) of the additional attribute.
   Name

   ;; Free-text description of the additional attribute.
   Description

   ;; The date this additional attribute information was updated.
   UpdateDate

   ;; The maximum value of the additional attribute over the whole collection.
   ParameterRangeEnd

   ;; Data type of the values of the additional attribute.
   DataType
  ])
(record-pretty-printer/enable-record-pretty-printing AdditionalAttributeType)

;; Information about any constraints for accessing the data set. This includes any special
;; restrictions, legal prerequisites, limitations and/or warnings on obtaining the data set.
(defrecord AccessConstraintsType
  [
   ;; Free-text description of the constraint. In DIF, this field is called Access_Constraint. In
   ;; ECHO, this field is called RestrictionComment. Examples of text in this field are Public,
   ;; In-house, Limited. Additional detailed instructions on how to access the collection data may
   ;; be entered in this field.
   Description

   ;; Numeric value that is used with Access Control Language (ACLs) to restrict access to this
   ;; collection. For example, a provider might specify a collection level ACL that hides all
   ;; collections with a value element set to 15. In ECHO, this field is called RestrictionFlag.
   ;; This field does not exist in DIF.
   Value
  ])
(record-pretty-printer/enable-record-pretty-printing AccessConstraintsType)

;; Represents the information needed for a DistributionURL where data is retrieved.
(defrecord GetDataType
  [
   ;; The format of the data. The controlled vocabulary for formats is maintained in the Keyword
   ;; Management System (KMS)
   Format

   ;; The mime type of the service.
   MimeType

   ;; The size of the data.
   Size

   ;; Unit of information, together with Size determines total size in bytes of the data.
   Unit

   ;; The fee for ordering the collection data. The fee is entered as a number, in US Dollars.
   Fees

   ;; The checksum, usually a SHA1 or md5 checksum for the data file.
   Checksum
  ])
(record-pretty-printer/enable-record-pretty-printing GetDataType)

;; This element stores the DOI (Digital Object Identifier) that identifies the collection. Note: The
;; values should start with the directory indicator which in ESDIS' case is 10. If the DOI was
;; registered through ESDIS, the beginning of the string should be 10.5067. The DOI URL is not
;; stored here; it should be stored as a RelatedURL. The DOI organization that is responsible for
;; creating the DOI is described in the Authority element. For ESDIS records the value of
;; https://doi.org/ should be used. NASA metadata providers are strongly encouraged to include DOI
;; and DOI Authority for their collections using CollectionDOI property.
(defrecord DoiDoiType
  [
   ;; This element stores the DOI (Digital Object Identifier) that identifies the collection. Note:
   ;; The values should start with the directory indicator which in ESDIS' case is 10. If the DOI
   ;; was registered through ESDIS, the beginning of the string should be 10.5067. The DOI URL is
   ;; not stored here; it should be stored as a RelatedURL.
   DOI

   ;; The DOI organization that is responsible for creating the DOI is described in the Authority
   ;; element. For ESDIS records the value of https://doi.org/ should be used.
   Authority
  ])
(record-pretty-printer/enable-record-pretty-printing DoiDoiType)

;; Describes key bibliographic citations pertaining to the data.
(defrecord PublicationReferenceType
  [
   ;; The date of the publication.
   PublicationDate

   ;; Additional free-text reference information about the publication.
   OtherReferenceDetails

   ;; The name of the series of the publication.
   Series

   ;; The title of the publication in the bibliographic citation.
   Title

   ;; The Digital Object Identifier (DOI) of the publication.
   DOI

   ;; The publication pages that are relevant.
   Pages

   ;; The edition of the publication.
   Edition

   ;; The report number of the publication.
   ReportNumber

   ;; The publication volume number.
   Volume

   ;; The URL of the website related to the bibliographic citation.
   OnlineResource

   ;; The publisher of the publication.
   Publisher

   ;; The ISBN of the publication.
   ISBN

   ;; The author of the publication.
   Author

   ;; The issue of the publication.
   Issue

   ;; The publication place of the publication.
   PublicationPlace
  ])
(record-pretty-printer/enable-record-pretty-printing PublicationReferenceType)

;; Used to identify other services, collections, visualizations, granules, and other metadata types
;; and resources that are associated with or dependent on this collection, including parent-child
;; relationships.
(defrecord MetadataAssociationType
  [
   ;; The type of association between this collection metadata record and the target metadata
   ;; record. Choose type from the drop-down list.
   Type

   ;; Free-text description of the association between this collection record and the target
   ;; metadata record.
   Description

   ;; ShortName of the target metadata record that is associated with this collection record.
   EntryId

   ;; The version of the target metadata record that is associated with this collection record.
   Version
  ])
(record-pretty-printer/enable-record-pretty-printing MetadataAssociationType)

(defrecord ContactPersonType
  [
   ;; This is the roles of the data contact.
   Roles

   ;; Uuid of the data contact.
   Uuid

   ;; This is the contact person or group that is not affiliated with the data centers.
   NonDataCenterAffiliation

   ;; This is the contact information of the data contact.
   ContactInformation

   ;; First name of the individual.
   FirstName

   ;; Middle name of the individual.
   MiddleName

   ;; Last name of the individual.
   LastName
  ])
(record-pretty-printer/enable-record-pretty-printing ContactPersonType)

;; Specifies the date and its type.
(defrecord DateType
  [
   ;; This is the date that an event associated with the collection or its metadata occurred.
   Date

   ;; This is the type of event associated with the date. For example, Creation, Last Revision. Type
   ;; is chosen from a picklist.
   Type
  ])
(record-pretty-printer/enable-record-pretty-printing DateType)

;; This entity is used to define characteristics.
(defrecord CharacteristicType
  [
   ;; The name of the characteristic attribute.
   Name

   ;; Description of the Characteristic attribute.
   Description

   ;; The value of the Characteristic attribute.
   Value

   ;; Units associated with the Characteristic attribute value.
   Unit

   ;; The datatype of the Characteristic/attribute.
   DataType
  ])
(record-pretty-printer/enable-record-pretty-printing CharacteristicType)

;; Describes the online resource pertaining to the data.
(defrecord OnlineResourceType
  [
   ;; The URL of the website related to the online resource.
   Linkage

   ;; The protocol of the linkage for the online resource, such as https, svn, ftp, etc.
   Protocol

   ;; The application profile holds the name of the application that can service the data. For
   ;; example if the URL points to a word document, then the applicationProfile is MS-Word.
   ApplicationProfile

   ;; The name of the online resource.
   Name

   ;; The description of the online resource.
   Description

   ;; The function of the online resource. In ISO where this class originated the valid values are:
   ;; download, information, offlineAccess, order, and search.
   Function

   ;; The mime type of the online resource.
   MimeType
  ])
(record-pretty-printer/enable-record-pretty-printing OnlineResourceType)

;; Information which describes the temporal range or extent of a specific collection.
(defrecord TemporalExtentType
  [
   ;; The precision (position in number of places to right of decimal point) of seconds used in
   ;; measurement.
   PrecisionOfSeconds

   ;; Setting the Ends At Present Flag to 'True' indicates that a data collection which covers,
   ;; temporally, a discontinuous range, currently ends at the present date. Setting the Ends at
   ;; Present flag to 'True' eliminates the need to continuously update the Range Ending Time for
   ;; collections where granules are continuously being added to the collection inventory.
   EndsAtPresentFlag

   ;; Stores the start and end date/time of a collection.
   RangeDateTimes

   SingleDateTimes

   ;; Temporal information about a collection having granules collected at a regularly occurring
   ;; period. Information includes the start and end dates of the period, duration unit and value,
   ;; and cycle duration unit and value.
   PeriodicDateTimes
  ])
(record-pretty-printer/enable-record-pretty-printing TemporalExtentType)

;; Represents Internet sites that contain information related to the data, as well as related
;; Internet sites such as project home pages, related data archives/servers, metadata extensions,
;; online software packages, web mapping services, and calibration/validation data.
(defrecord RelatedUrlType
  [
   ;; Description of the web page at this URL.
   Description

   ;; A keyword describing the distinct content type of the online resource to this resource. (e.g.,
   ;; 'DATACENTER URL', 'DATA CONTACT URL', 'DISTRIBUTION URL'). The valid values are contained in
   ;; the KMS System:
   ;; https://gcmd.earthdata.nasa.gov/KeywordViewer/scheme/all/8759ab63-ac04-4136-bc25-0c00eece1096?gtm_keyword=Related%20URL%20Content%20Types&gtm_scheme=rucontenttype.
   URLContentType

   ;; A keyword describing the type of the online resource to this resource. This helps the GUI to
   ;; know what to do with this resource. (e.g., 'GET DATA', 'GET SERVICE', 'GET VISUALIZATION').
   ;; The valid values are contained in the KMS System:
   ;; https://gcmd.earthdata.nasa.gov/KeywordViewer/scheme/all/8759ab63-ac04-4136-bc25-0c00eece1096?gtm_keyword=Related%20URL%20Content%20Types&gtm_scheme=rucontenttype.
   Type

   ;; A keyword describing the subtype of the online resource to this resource. This further helps
   ;; the GUI to know what to do with this resource. (e.g., 'MEDIA', 'BROWSE', 'OPENDAP',
   ;; 'OPENSEARCH', 'WEB COVERAGE SERVICES', 'WEB FEATURE SERVICES', 'WEB MAPPING SERVICES', 'SSW',
   ;; 'ESI'). The valid values are contained in the KMS System:
   ;; https://gcmd.earthdata.nasa.gov/KeywordViewer/scheme/all/8759ab63-ac04-4136-bc25-0c00eece1096?gtm_keyword=Related%20URL%20Content%20Types&gtm_scheme=rucontenttype.
   Subtype

   ;; The URL for the relevant web page (e.g., the URL of the responsible organization's home page,
   ;; the URL of the collection landing page, the URL of the download site for the collection).
   URL

   ;; The data distribution information for the relevant web page (e.g., browse, media).
   GetData

   ;; The service distribution for the relevant web page (e.g., OPeNDAP, OpenSearch, WCS, WFS, WMS).
   GetService
  ])
(record-pretty-printer/enable-record-pretty-printing RelatedUrlType)

;; Information about Periodic Date Time collections, including the name of the temporal period in
;; addition to the start and end dates, duration unit and value, and cycle duration unit and value.
(defrecord PeriodicDateTimeType
  [
   ;; The name given to the recurring time period. e.g. 'spring - north hemi.'
   Name

   ;; The date (day and time) of the first occurrence of this regularly occurring period which is
   ;; relevant to the collection coverage.
   StartDate

   ;; The date (day and time) of the end occurrence of this regularly occurring period which is
   ;; relevant to the collection coverage.
   EndDate

   ;; The unit specification for the period duration.
   DurationUnit

   ;; The number of PeriodDurationUnits in the RegularPeriodic period. e.g. the RegularPeriodic
   ;; event 'Spring-North Hemi' might have a PeriodDurationUnit='MONTH' PeriodDurationValue='3'
   ;; PeriodCycleDurationUnit='YEAR' PeriodCycleDurationValue='1' indicating that Spring-North Hemi
   ;; lasts for 3 months and has a cycle duration of 1 year. The unit for the attribute is the value
   ;; of the attribute PeriodDurationValue.
   DurationValue

   ;; The unit specification of the period cycle duration.
   PeriodCycleDurationUnit

   PeriodCycleDurationValue
  ])
(record-pretty-printer/enable-record-pretty-printing PeriodicDateTimeType)

;; Represents a Service through a URL where the service will act on data and return the result to
;; the caller.
(defrecord GetServiceType
  [
   ;; The format of the data.
   Format

   ;; The mime type of the service.
   MimeType

   ;; The protocol of the service.
   Protocol

   ;; The full name of the service.
   FullName

   ;; The data identifier of the data provided by the service. Typically, this is a file name.
   DataID

   ;; The data type of the data provided by the service.
   DataType

   ;; The URI of the data provided by the service.
   URI
  ])
(record-pretty-printer/enable-record-pretty-printing GetServiceType)

;; This entity contains the physical address details for the contact.
(defrecord AddressType
  [
   ;; An address line for the street address, used for mailing or physical addresses of
   ;; organizations or individuals who serve as contacts for the collection.
   StreetAddresses

   ;; The city portion of the physical address.
   City

   ;; The state or province portion of the physical address.
   StateProvince

   ;; The country of the physical address.
   Country

   ;; The zip or other postal code portion of the physical address.
   PostalCode
  ])
(record-pretty-printer/enable-record-pretty-printing AddressType)