;; WARNING: This file was generated from umm-var-json-schema.json. Do not manually modify.
(ns cmr.umm-spec.models.umm-variable-models
   "Defines UMM-Var clojure records."
 (:require [cmr.common.dev.record-pretty-printer :as record-pretty-printer]))

(defrecord UMM-Var
  [
   ;; Valid range data value of a variable: minimum and maximum values. For example. '7500, -1', or
   ;; '0, 377'.
   ValidRange

   ;; The service information of a variable.
   Service

   Dimensions

   ;; Scale factor which has been applied to the cell value. For example, '0.002'
   Scale

   ;; The physical value corresponding to a cell value of zero. For example, '0.49'.
   Offset

   ;; The set information of a variable.
   Set

   ;; The fill value of the variable in the data file. It is generally a value which falls outside
   ;; the valid range. For example, if the valid range is '0, 360', the fill value may be '-1'.
   FillValue

   ;; The units associated with a variable.
   Units

   ;; The definition of the variable.
   Definition

   ;; The measurement information of a variable.
   Measurements

   ;; The characteristics of a variable. The elements of this section apply to a Variable.
   Characteristics

   ;; Controlled Science Keywords describing the measurements/variables. The controlled vocabulary
   ;; for Science Keywords is maintained in the Keyword Management System (KMS).
   ScienceKeywords

   ;; The name of a variable.
   Name

   ;; Specify basic type of a variable. These types can be either: Science, Ancillary, Quality etc.
   VariableType

   ;; The descriptive name for the variable.
   LongName

   ;; Specify data type of a variable. These types can be either: uint8, uint16, etc.
   DataType
  ])
(record-pretty-printer/enable-record-pretty-printing UMM-Var)

;; The elements of this section apply to the fill value of a variable.
(defrecord FillValueType
  [
   ;; The fill value of the variable in the data file.
   Value

   ;; Type of the fill value of the variable in the data file.
   Type

   ;; Description of the fill value of the variable in the data file.
   Description
  ])
(record-pretty-printer/enable-record-pretty-printing FillValueType)

;; Valid range data value of a variable: minimum and maximum values. For example. '-100, 5000'.
(defrecord ValidRangeType
  [
   ;; Minimum data value of a variable.
   Min

   ;; Maximum data value of a variable.
   Max
  ])
(record-pretty-printer/enable-record-pretty-printing ValidRangeType)

;; The elements of this section apply to a measurement.
(defrecord MeasurementsType
  [
   ;; This element allows authors to provide community sourced words or phrases to further describe
   ;; the variable data.
   MeasurementName

   ;; This element allows authors to identify the source of the measurements.
   MeasurementSource
  ])
(record-pretty-printer/enable-record-pretty-printing MeasurementsType)

;; The elements of this section apply to a variable.
(defrecord CharacteristicsType
  [
   ;; Describes the spatial bounds of a variable. Western Longitude, Northern Latitude and Eastern
   ;; Longitude, Southern Latitude - often specified in decimal degrees. For example,
   ;; 'UpperLeftPointMtrs = -180.0, 89.5; LowerRightMtrs = 177.5, -89.5.'
   Bounds

   ;; The computed byte size for the variable, per the data field. Typically, this is the X
   ;; dimension times the Y dimension times the number of bytes in the data type (8, 16, 32, etc.).
   ;; For example, 1200 x 1200 x 16 = 23,040,000.
   Size

   ;; This is a string containing the structure of the variable. This is sourced from the granule
   ;; header. See the variables section.
   Structure

   ;; The measurement conditions of the variable.
   MeasurementConditions

   ;; A variable’s coordinates. These are used to describe how the variable is represented with
   ;; respect to the Earth geoid.
   Coordinates

   ;; Describes the chunk size of a variable. For example, '100'.
   ChunkSize

   ;; The name of the mapping projection standard for the variable. For example: Mercator. This is
   ;; sourced from the granule header. See the global attributes section.
   GridMapping

   ;; The reporting conditions of the variable.
   ReportingConditions

   ;; The computed byte size units for the variable, per the data field. For example B, KB, MB, GB.
   SizeUnits

   ;; The CF-compliant 'Standard Name' for the variable.
   StandardName

   ;; Provides a link to variable's reference documentation.
   Reference
  ])
(record-pretty-printer/enable-record-pretty-printing CharacteristicsType)

;; The elements of this section apply to a variable.
(defrecord SetType
  [
   ;; This element enables specification of set name. The variable may grouped within a set. The set
   ;; is defined by the name, type, size and index. For example, some variables exist in pairs or
   ;; sets of three or more.
   Name

   ;; This element enables specification of set type. The variable may grouped within a set. The set
   ;; is defined by the name, type, size and index. For example, some variables exist in pairs or
   ;; sets of three or more.
   Type

   ;; This element specifies the size of the set.
   Size

   ;; This element specifies the index value within the set for this variable, i.e. 1,2,3.
   Index
  ])
(record-pretty-printer/enable-record-pretty-printing SetType)

;; The elements of this section apply to a variable.
(defrecord DimensionsType
  [
   ;; The names of the dimensions of the variable represented in the data field. For example, 'XDim,
   ;; YDim'.
   Name

   ;; The values of the dimensions of the variable represented in the data field. For example,
   ;; '1200, 1200'.
   Size
  ])
(record-pretty-printer/enable-record-pretty-printing DimensionsType)

;; The elements of this section apply to a variable.
(defrecord ServiceType
  [
   ;; This element enables specification of service type. The variable may not yet be available via
   ;; a service. If so, which protocol standard? For example, 'WMS', 'WCS' etc.
   ServiceType

   ;; A flag to indicate whether this variable is able to be visualized within the context of a
   ;; service.
   Visualizable

   ;; A flag to indicate whether this variable is able to be subsetted within the context of a
   ;; service.
   Subsettable
  ])
(record-pretty-printer/enable-record-pretty-printing ServiceType)