;; WARNING: This file was generated from umm-g-json-schema.json. Do not manually modify.
(ns cmr.umm-spec.models.umm-granule-models
   "Defines UMM-G clojure records."
 (:require [cmr.common.dev.record-pretty-printer :as record-pretty-printer]))

(defrecord UMM-G
  [
   ;; This entity contains the name of the geophysical parameter expressed in the data as well as
   ;; associated quality flags and quality statistics. The quality statistics element contains
   ;; measures of quality for the granule. The parameters used to set these measures are not preset
   ;; and will be determined by the data producer. Each set of measures can occur many times either
   ;; for the granule as a whole or for individual parameters. The quality flags contain the
   ;; science, operational and automatic quality flags which indicate the overall quality assurance
   ;; levels of specific parameter values within a granule.
   MeasuredParameters

   ;; This entity stores basic descriptive characteristics related to the Product Generation
   ;; Executable associated with a granule.
   PGEVersionClass

   ;; This entity stores the tiling identification system for the granule. The tiling identification
   ;; system information is an alternative way to express granule's spatial coverage based on a
   ;; certain two dimensional coordinate system defined by the providers. The name must match the
   ;; name in the parent collection.
   TilingIdentificationSystem

   ;; A percentage value indicating how much of the area of a granule (the EOSDIS data unit) has
   ;; been obscured by clouds. It is worth noting that there are many different measures of cloud
   ;; cover within the EOSDIS data holdings and that the cloud cover parameter that is represented
   ;; in the archive is dataset-specific.
   CloudCover

   ;; Represents the native projection of the granule if the granule has a native projection.
   NativeProjectionNames

   ;; This element describes any data/service related URLs that include project home pages,
   ;; services, related data archives/servers, metadata extensions, direct links to online software
   ;; packages, web mapping services, links to images, or other data.
   RelatedUrls

   ;; Allows the author to constrain access to the granule. Some words that may be used in this
   ;; element's value include: Public, In-house, Limited, None. The value field is used for special
   ;; ACL rules (Access Control Lists (http://en.wikipedia.org/wiki/Access_control_list)). For
   ;; example it can be used to hide metadata when it isn't ready for public consumption.
   AccessConstraints

   ;; This class contains attributes which describe the spatial extent of a granule. Spatial Extent
   ;; includes any or all of Granule Localities, Horizontal Spatial Domain, and Vertical Spatial
   ;; Domain.
   SpatialExtent

   ;; Dates related to activities involving the the granule and the data provider database with the
   ;; exception for Delete. For Create, Update, and Insert the date is the date that the granule
   ;; file is created, updated, or inserted into the provider database by the provider. Delete is
   ;; the date that the CMR should delete the granule metadata record from its repository.
   ProviderDates

   ;; Reference to an additional attribute in the parent collection. The attribute reference may
   ;; contain a granule specific value that will override the value in the parent collection for
   ;; this granule. An attribute with the same name must exist in the parent collection.
   AdditionalAttributes

   ;; The collection metadata record's short name and version, or entry title to which this granule
   ;; metadata record belongs.
   CollectionReference

   ;; This entity stores basic descriptive characteristics associated with a granule.
   DataGranule

   ;; This entity is used to store the characteristics of the orbit calculated spatial domain to
   ;; include the model name, orbit number, start and stop orbit number, equator crossing date and
   ;; time, and equator crossing longitude.
   OrbitCalculatedSpatialDomains

   ;; A reference to a platform in the parent collection that is associated with the acquisition of
   ;; the granule. The platform must exist in the parent collection. For example, Platform types may
   ;; include (but are not limited to): ADEOS-II, AEM-2, Terra, Aqua, Aura, BALLOONS, BUOYS, C-130,
   ;; DEM, DMSP-F1,etc.
   Platforms

   ;; This class contains attributes which describe the temporal extent of a granule. Temporal
   ;; Extent includes either a Range Date Time, or a Single Date Time
   TemporalExtent

   ;; The Universal Reference ID of the granule referred by the data provider. This ID is unique per
   ;; data provider.
   GranuleUR

   ;; The name of the scientific program, field campaign, or project from which the data were
   ;; collected. This element is intended for the non-space assets such as aircraft, ground systems,
   ;; balloons, sondes, ships, etc. associated with campaigns. This element may also cover a long
   ;; term project that continuously creates new data sets — like MEaSUREs from ISCCP and NVAP or
   ;; CMARES from MISR. Project also includes the Campaign sub-element to support multiple campaigns
   ;; under the same project.
   Projects

   ;; Requires the user to add in schema information into every granule record. It includes the
   ;; schema's name, version, and URL location. The information is controlled through enumerations
   ;; at the end of this schema.
   MetadataSpecification

   ;; Represents the native grid mapping of the granule, if the granule is gridded.
   GridMappingNames

   ;; This entity contains the identification of the input granule(s) for a specific granule.
   InputGranules
  ])
(record-pretty-printer/enable-record-pretty-printing UMM-G)

;; A reference to a platform in the parent collection that is associated with the acquisition of the
;; granule. The platform must exist in the parent collection. For example, Platform types may
;; include (but are not limited to): ADEOS-II, AEM-2, Terra, Aqua, Aura, BALLOONS, BUOYS, C-130,
;; DEM, DMSP-F1,etc.
(defrecord PlatformType
  [
   ShortName

   ;; References to the devices in the parent collection that were used to measure or record data,
   ;; including direct human observation.
   Instruments
  ])
(record-pretty-printer/enable-record-pretty-printing PlatformType)

;; Information describing the scientific endeavor with which the granule is associated.
(defrecord ProjectType
  [
   ;; The unique identifier by which a project is known. The project is the scientific endeavor
   ;; associated with the acquisition of the collection.
   ShortName

   ;; The name of the campaign/experiment (e.g. Global climate observing system).
   Campaigns
  ])
(record-pretty-printer/enable-record-pretty-printing ProjectType)

;; A reference to the device in the parent collection that was used to measure or record data,
;; including direct human observation. In cases where instruments have a single composed of child
;; instrument (sensor) or the instrument and composed of child instrument (sensor) are used
;; synonymously (e.g. AVHRR) the both Instrument and composed of child instrument should be
;; recorded. The child instrument information is represented by child entities. The instrument
;; reference may contain granule specific characteristics and operation modes. These characteristics
;; and modes are not checked against the referenced instrument.
(defrecord InstrumentType
  [
   ShortName

   ;; This entity is used to define item additional attributes (unprocessed, custom data).
   Characteristics

   ;; References to instrument subcomponents in the parent collection's instrument used by various
   ;; sources in the granule. An instrument subcomponent reference may contain characteristics
   ;; specific to the granule.
   ComposedOf

   ;; This entity identifies the instrument's operational modes for a specific collection associated
   ;; with the channel, wavelength, and FOV (e.g., launch, survival, initialization, safe,
   ;; diagnostic, standby, crosstrack, biaxial, solar calibration).
   OperationalModes
  ])
(record-pretty-printer/enable-record-pretty-printing InstrumentType)

;; This entity is used to store the characteristics of the orbit calculated spatial domain to
;; include the model name, orbit number, start and stop orbit number, equator crossing date and
;; time, and equator crossing longitude.
(defrecord OrbitCalculatedSpatialDomainType
  [
   ;; The reference to the orbital model to be used to calculate the geo-location of this data in
   ;; order to determine global spatial extent.
   OrbitalModelName

   ;; The orbit number to be used in calculating the spatial extent of this data.
   OrbitNumber

   ;; Orbit number at the start of the data granule.
   BeginOrbitNumber

   ;; Orbit number at the end of the data granule.
   EndOrbitNumber

   ;; This attribute represents the terrestrial longitude of the descending equator crossing.
   EquatorCrossingLongitude

   ;; This attribute represents the date and time of the descending equator crossing.
   EquatorCrossingDateTime
  ])
(record-pretty-printer/enable-record-pretty-printing OrbitCalculatedSpatialDomainType)

;; Information about a granule with horizontal spatial coverage.
(defrecord HorizontalSpatialDomainType
  [
   ;; The appropriate numeric or alpha code used to identify the various zones in the granule's grid
   ;; coordinate system.
   ZoneIdentifier

   ;; This entity holds the geometry representing the spatial coverage information of a granule.
   Geometry

   ;; This entity stores orbital coverage information of the granule. This coverage is an
   ;; alternative way of expressing granule spatial coverage. This information supports orbital
   ;; backtrack searching on a granule.
   Orbit

   ;; This element stores track information of the granule. Track information is used to allow a
   ;; user to search for granules whose spatial extent is based on an orbital cycle, pass, and tile
   ;; mapping. Though it is derived from the SWOT mission requirements, it is intended that this
   ;; element type be generic enough so that other missions can make use of it. While track
   ;; information is a type of spatial domain, it is expected that the metadata provider will
   ;; provide geometry information that matches the spatial extent of the track information.
   Track
  ])
(record-pretty-printer/enable-record-pretty-printing HorizontalSpatialDomainType)

;; Contains the excluded boundaries from the GPolygon.
(defrecord ExclusiveZoneType
  [
   Boundaries
  ])
(record-pretty-printer/enable-record-pretty-printing ExclusiveZoneType)

;; This object requires any metadata record that is validated by this schema to provide information
;; about the schema.
(defrecord MetadataSpecificationType
  [
   ;; This element represents the URL where the schema lives. The schema can be downloaded.
   URL

   ;; This element represents the name of the schema.
   Name

   ;; This element represents the version of the schema.
   Version
  ])
(record-pretty-printer/enable-record-pretty-printing MetadataSpecificationType)

;; This entity stores the tiling identification system for the granule. The tiling identification
;; system information is an alternative way to express granule's spatial coverage based on a certain
;; two dimensional coordinate system defined by the providers. The name must match the name in the
;; parent collection.
(defrecord TilingIdentificationSystemType
  [
   TilingIdentificationSystemName

   Coordinate1

   Coordinate2
  ])
(record-pretty-printer/enable-record-pretty-printing TilingIdentificationSystemType)

;; This class contains attributes which describe the spatial extent of a granule. Spatial Extent
;; includes any or all of Granule Localities, Horizontal Spatial Domain, and Vertical Spatial
;; Domain.
(defrecord SpatialExtentType
  [
   ;; This entity stores information used at the granule level to describe the labeling of granules
   ;; with compounded time/space text values and which are subsequently used to define more
   ;; phenomenological-based granules, thus the locality type and description are contained.
   GranuleLocalities

   ;; This represents the granule horizontal spatial domain information.
   HorizontalSpatialDomain

   ;; This represents the domain value and type for the granule's vertical spatial domain.
   VerticalSpatialDomains
  ])
(record-pretty-printer/enable-record-pretty-printing SpatialExtentType)

;; Allows the provider to provide a checksum value and checksum algorithm name to allow the user to
;; calculate the checksum.
(defrecord ChecksumType
  [
   ;; Describes the checksum value for a file.
   Value

   ;; The algorithm name by which the checksum was calulated. This allows the user to re-calculate
   ;; the checksum to verify the integrity of the downloaded data.
   Algorithm
  ])
(record-pretty-printer/enable-record-pretty-printing ChecksumType)

;; This entity contains the name of the geophysical parameter expressed in the data as well as
;; associated quality flags and quality statistics. The quality statistics element contains measures
;; of quality for the granule. The parameters used to set these measures are not preset and will be
;; determined by the data producer. Each set of measures can occur many times either for the granule
;; as a whole or for individual parameters. The quality flags contain the science, operational and
;; automatic quality flags which indicate the overall quality assurance levels of specific parameter
;; values within a granule.
(defrecord MeasuredParameterType
  [
   ;; The measured science parameter expressed in the data granule.
   ParameterName

   ;; The associated quality statistics.
   QAStats

   ;; The associated quality flags.
   QAFlags
  ])
(record-pretty-printer/enable-record-pretty-printing MeasuredParameterType)

;; Specifies the date and its type that the provider uses for the granule. For Create, Update, and
;; Insert the date is the date that the granule file is created, updated, or inserted into the
;; provider database by the provider. Delete is the date that the CMR should delete the granule
;; metadata record from its repository.
(defrecord ProviderDateType
  [
   ;; This is the date that an event associated with the granule occurred.
   Date

   ;; This is the type of event associated with the date. For example, Creation or Upate.
   Type
  ])
(record-pretty-printer/enable-record-pretty-printing ProviderDateType)

;; Stores the data acquisition start and end date/time for a granule.
(defrecord RangeDateTimeType
  [
   ;; The time when the temporal coverage period being described began.
   BeginningDateTime

   ;; The time when the temporal coverage period being described ended.
   EndingDateTime
  ])
(record-pretty-printer/enable-record-pretty-printing RangeDateTimeType)

;; This entity stores an identifier. If the identifier is part of the enumeration then use it. If
;; the enumeration is 'Other', the provider must specify the identifier's name.
(defrecord IdentifierType
  [
   ;; The identifier value.
   Identifier

   ;; The enumeration of known identifier types.
   IdentifierType

   ;; The Name of identifier.
   IdentifierName
  ])
(record-pretty-printer/enable-record-pretty-printing IdentifierType)

;; This entity holds the horizontal spatial coverage of a bounding box.
(defrecord BoundingRectangleType
  [
   WestBoundingCoordinate

   NorthBoundingCoordinate

   EastBoundingCoordinate

   SouthBoundingCoordinate
  ])
(record-pretty-printer/enable-record-pretty-printing BoundingRectangleType)

;; This entity holds the horizontal spatial coverage of a line. A line area contains at lease two
;; points.
(defrecord LineType
  [
   Points
  ])
(record-pretty-printer/enable-record-pretty-printing LineType)

;; The quality flags contain the science, operational and automatic quality flags which indicate the
;; overall quality assurance levels of specific parameter values within a granule.
(defrecord QAFlagsType
  [
   ;; The granule level flag applying generally to the granule and specifically to parameters the
   ;; granule level. When applied to parameter, the flag refers to the quality of that parameter for
   ;; the granule (as applicable). The parameters determining whether the flag is set are defined by
   ;; the developer and documented in the Quality Flag Explanation.
   AutomaticQualityFlag

   ;; A text explanation of the criteria used to set automatic quality flag; including thresholds or
   ;; other criteria.
   AutomaticQualityFlagExplanation

   ;; The granule level flag applying both generally to a granule and specifically to parameters at
   ;; the granule level. When applied to parameter, the flag refers to the quality of that parameter
   ;; for the granule (as applicable). The parameters determining whether the flag is set are
   ;; defined by the developers and documented in the QualityFlagExplanation.
   OperationalQualityFlag

   ;; A text explanation of the criteria used to set operational quality flag; including thresholds
   ;; or other criteria.
   OperationalQualityFlagExplanation

   ;; Granule level flag applying to a granule, and specifically to parameters. When applied to
   ;; parameter, the flag refers to the quality of that parameter for the granule (as applicable).
   ;; The parameters determining whether the flag is set are defined by the developers and
   ;; documented in the Quality Flag Explanation.
   ScienceQualityFlag

   ;; A text explanation of the criteria used to set science quality flag; including thresholds or
   ;; other criteria.
   ScienceQualityFlagExplanation
  ])
(record-pretty-printer/enable-record-pretty-printing QAFlagsType)

;; A reference to an additional attribute in the parent collection. The attribute reference may
;; contain a granule specific value that will override the value in the parent collection for this
;; granule. An attribute with the same name must exist in the parent collection.
(defrecord AdditionalAttributeType
  [
   ;; The additional attribute's name.
   Name

   ;; Values of the additional attribute.
   Values
  ])
(record-pretty-printer/enable-record-pretty-printing AdditionalAttributeType)

;; This set of elements describes a file package or a file that contains other files. Normally this
;; is either a tar or a zip file.
(defrecord FilePackageType
  [
   ;; This field describes the name of the actual file.
   Name

   ;; The size in Bytes of the volume of data contained in the granule. Bytes are defined as eight
   ;; bits. Please use this element instead of or inclusive with the Size element. The issue with
   ;; the size element is that if CMR data providers use a unit other than Bytes, end users don't
   ;; know how the granule size was calculated. For example, if the unit was MegaBytes, the size
   ;; could be calculated by using 1000xE2 Bytes (MegaBytes) or 1024xE2 Bytes (mebibytes) and
   ;; therefore there is no systematic way to know the actual size of a granule by using the granule
   ;; metadata record.
   SizeInBytes

   ;; The size of the volume of data contained in the granule. Please use the SizeInBytes element
   ;; either instead of this one or inclusive of this one. The issue with the size element is that
   ;; if CMR data providers use a unit other than Bytes, end users don't know how the granule size
   ;; was calculated. For example, if the unit was MegaBytes, the size could be calculated by using
   ;; 1000xE2 Bytes (MegaBytes) or 1024xE2 Bytes (mebibytes) and therefore there is no systematic
   ;; way to know the actual size of a granule by using the granule metadata record.
   Size

   ;; The unit of the file size.
   SizeUnit

   ;; This element defines a single format for a distributable artifact.
   Format

   ;; The mime type of the resource.
   MimeType

   ;; Allows the provider to provide the checksum value for the file.
   Checksum

   ;; Allows the provider to add the list of the files that are included in this one.
   Files
  ])
(record-pretty-printer/enable-record-pretty-printing FilePackageType)

;; Information about any physical constraints for accessing the data set.
(defrecord AccessConstraintsType
  [
   ;; Free-text description of the constraint. In ECHO 10, this field is called RestrictionComment.
   ;; Additional detailed instructions on how to access the granule data may be entered in this
   ;; field.
   Description

   ;; Numeric value that is used with Access Control Language (ACLs) to restrict access to this
   ;; granule. For example, a provider might specify a granule level ACL that hides all granules
   ;; with a value element set to 15. In ECHO, this field is called RestrictionFlag.
   Value
  ])
(record-pretty-printer/enable-record-pretty-printing AccessConstraintsType)

;; This entity contains the type and value for the granule's vertical spatial domain.
(defrecord VerticalSpatialDomainType
  [
   ;; Describes the type of the area of vertical space covered by the granule locality.
   Type

   ;; Describes the extent of the area of vertical space covered by the granule. Use this for
   ;; Atmosphere profiles or for a specific value.
   Value

   ;; Describes the extent of the area of vertical space covered by the granule. Use this and
   ;; MaximumValue to represent a range of values (Min and Max).
   MinimumValue

   ;; Describes the extent of the area of vertical space covered by the granule. Use this and
   ;; MinimumValue to represent a range of values (Min and Max).
   MaximumValue

   ;; Describes the unit of the vertical extent value.
   Unit
  ])
(record-pretty-printer/enable-record-pretty-printing VerticalSpatialDomainType)

;; This entity holds the geometry representing the spatial coverage information of a granule.
(defrecord GeometryType
  [
   ;; The horizontal spatial coverage of a point.
   Points

   ;; This entity holds the horizontal spatial coverage of a bounding box.
   BoundingRectangles

   ;; A GPolygon specifies an area on the earth represented by a main boundary with optional
   ;; boundaries for regions excluded from the main boundary.
   GPolygons

   ;; This entity holds the horizontal spatial coverage of a line. A line area contains at least two
   ;; points.
   Lines
  ])
(record-pretty-printer/enable-record-pretty-printing GeometryType)

;; The longitude and latitude values of a spatially referenced point in degrees.
(defrecord PointType
  [
   Longitude

   Latitude
  ])
(record-pretty-printer/enable-record-pretty-printing PointType)

;; This element stores track information of the granule. Track information is used to allow a user
;; to search for granules whose spatial extent is based on an orbital cycle, pass, and tile mapping.
;; Though it is derived from the SWOT mission requirements, it is intended that this element type be
;; generic enough so that other missions can make use of it. While track information is a type of
;; spatial domain, it is expected that the metadata provider will provide geometry information that
;; matches the spatial extent of the track information.
(defrecord TrackType
  [
   ;; An integer that represents a specific set of orbital spatial extents defined by passes and
   ;; tiles. Though intended to be generic, this comes from a SWOT mission requirement where each
   ;; cycle represents a set of 1/2 orbits. Each 1/2 orbit is called a 'pass'. During science mode,
   ;; a cycle represents 21 days of 14 full orbits or 588 passes.
   Cycle

   ;; A pass number identifies a subset of a granule's spatial extent. This element holds a list of
   ;; pass numbers and their tiles that exist in the granule. It will allow a user to search by pass
   ;; number and its tiles that are contained with in a cycle number. While trying to keep this
   ;; generic for all to use, this comes from a SWOT requirement where a pass represents a 1/2
   ;; orbit. This element will then hold a list of 1/2 orbits and their tiles that together
   ;; represent the granule's spatial extent.
   Passes
  ])
(record-pretty-printer/enable-record-pretty-printing TrackType)

;; This entity stores orbital coverage information of the granule. This coverage is an alternative
;; way of expressing granule spatial coverage. This information supports orbital backtrack searching
;; on a granule.
(defrecord OrbitType
  [
   ;; Equatorial crossing on the ascending pass in decimal degrees longitude. The convention we've
   ;; been using is it's the first included ascending crossing if one is included, and the prior
   ;; ascending crossing if none is included (e.g. descending half orbits).
   AscendingCrossing

   ;; Granule's starting latitude.
   StartLatitude

   ;; Ascending or descending. Valid input: 'A' or 'D'
   StartDirection

   ;; Granule's ending latitude.
   EndLatitude

   ;; Ascending or descending. Valid input: 'A' or 'D'
   EndDirection
  ])
(record-pretty-printer/enable-record-pretty-printing OrbitType)

;; Defines the minimum and maximum value for one dimension of a two dimensional coordinate system.
(defrecord TilingCoordinateType
  [
   MinimumValue

   MaximumValue
  ])
(record-pretty-printer/enable-record-pretty-printing TilingCoordinateType)

;; This entity stores the basic descriptive characteristics associated with a granule.
(defrecord DataGranuleType
  [
   ;; A list of the file(s) or file package(s) that make up the granule. A file package is something
   ;; like a tar or zip file.
   ArchiveAndDistributionInformation

   ;; Granule level, stating what reprocessing may be performed on this granule.
   ReprocessingPlanned

   ;; Granule level, stating what reprocessing has been performed on this granule.
   ReprocessingActual

   ;; This attribute is used to identify if a granule was collected during the day, night (between
   ;; sunset and sunrise) or both.
   DayNightFlag

   ;; The date and time a specific granule was produced by a PGE.
   ProductionDateTime

   ;; This holds any granule identifiers the provider wishes to provide.
   Identifiers
  ])
(record-pretty-printer/enable-record-pretty-printing DataGranuleType)

;; A GPolygon specifies an area on the earth represented by a main boundary with optional boundaries
;; for regions excluded from the main boundary.
(defrecord GPolygonType
  [
   Boundary

   ExclusiveZone
  ])
(record-pretty-printer/enable-record-pretty-printing GPolygonType)

;; A boundary is set of points connected by straight lines representing a polygon on the earth. It
;; takes a minimum of three points to make a boundary. Points must be specified in counter-clockwise
;; order and closed (the first and last vertices are the same).
(defrecord BoundaryType
  [
   Points
  ])
(record-pretty-printer/enable-record-pretty-printing BoundaryType)

;; This entity is used to reference characteristics defined in the parent collection.
(defrecord CharacteristicType
  [
   ;; The name of the characteristic attribute.
   Name

   ;; The value of the Characteristic attribute.
   Value
  ])
(record-pretty-printer/enable-record-pretty-printing CharacteristicType)

;; This set of elements describes a file. The file can be a part of the entire granule or is the
;; granule.
(defrecord FileType
  [
   ;; This field describes the name of the actual file.
   Name

   ;; The size in Bytes of the volume of data contained in the granule. Bytes are defined as eight
   ;; bits. Please use this element instead of or inclusive with the Size element. The issue with
   ;; the size element is that if CMR data providers use a unit other than Bytes, end users don't
   ;; know how the granule size was calculated. For example, if the unit was MegaBytes, the size
   ;; could be calculated by using 1000xE2 Bytes (MegaBytes) or 1024xE2 Bytes (mebibytes) and
   ;; therefore there is no systematic way to know the actual size of a granule by using the granule
   ;; metadata record.
   SizeInBytes

   ;; The size of the volume of data contained in the granule. Please use the SizeInBytes element
   ;; either instead of this one or inclusive of this one. The issue with the size element is that
   ;; if CMR data providers use a unit other than Bytes, end users don't know how the granule size
   ;; was calculated. For example, if the unit was MegaBytes, the size could be calculated by using
   ;; 1000xE2 Bytes (MegaBytes) or 1024xE2 Bytes (mebibytes) and therefore there is no systematic
   ;; way to know the actual size of a granule by using the granule metadata record.
   Size

   ;; The unit of the file size.
   SizeUnit

   ;; This element defines a single format for a distributable artifact.
   Format

   ;; Allows the provider to state whether the distributable item's format is its native format or
   ;; another supported format.
   FormatType

   ;; The mime type of the resource.
   MimeType

   ;; Allows the provider to provide the checksum value for the file.
   Checksum
  ])
(record-pretty-printer/enable-record-pretty-printing FileType)

;; Information which describes the temporal extent of a specific granule.
(defrecord TemporalExtentType
  [
   ;; Stores the data acquisition start and end date/time for a granule.
   RangeDateTime

   ;; Stores the data acquisition date/time for a granule.
   SingleDateTime
  ])
(record-pretty-printer/enable-record-pretty-printing TemporalExtentType)

;; This entity holds all types of online URL associated with the granule such as guide document or
;; ordering site etc.
(defrecord RelatedUrlType
  [
   ;; The URL for the relevant resource.
   URL

   ;; A keyword describing the type of the online resource to this resource.
   Type

   ;; A keyword that provides more detailed information than Type of the online resource to this
   ;; resource. For example if the Type=VIEW RELATED INFORMATION then the Subtype can be USER'S
   ;; GUIDE or GENERAL DOCUMENTATION
   Subtype

   ;; Description of the web page at this URL.
   Description

   ;; The format of the resource.
   Format

   ;; The mime type of the resource.
   MimeType

   ;; The size of the resource.
   Size

   ;; Unit of information, together with Size determines total size in bytes of the resource.
   SizeUnit
  ])
(record-pretty-printer/enable-record-pretty-printing RelatedUrlType)

;; This element stores a track pass and its tile information. It will allow a user to search by pass
;; number and their tiles that are contained with in a cycle number. While trying to keep this
;; generic for all to use, this comes from a SWOT requirement where a pass represents a 1/2 orbit.
;; This element will then hold a list of 1/2 orbits and their tiles that together represent the
;; granules spatial extent.
(defrecord TrackPassTileType
  [
   ;; A pass number identifies a subset of a granule's spatial extent. This element holds a pass
   ;; number that exists in the granule and will allow a user to search by pass number that is
   ;; contained within a cycle number. While trying to keep this generic for all to use, this comes
   ;; from a SWOT requirement where a pass represents a 1/2 orbit.
   Pass

   ;; A tile is a subset of a pass' spatial extent. This element holds a list of tile identifiers
   ;; that exist in the granule and will allow a user to search by tile identifier that is contained
   ;; within a pass number within a cycle number. Though intended to be generic, this comes from a
   ;; SWOT mission requirement where a tile is a spatial extent that encompasses either a square
   ;; scanning swath to the left or right of the ground track or a rectangle that includes a full
   ;; scanning swath both to the left and right of the ground track.
   Tiles
  ])
(record-pretty-printer/enable-record-pretty-printing TrackPassTileType)

;; This entity stores basic descriptive characteristics related to the Product Generation Executable
;; associated with a granule.
(defrecord PGEVersionClassType
  [
   ;; Name of product generation executable.
   PGEName

   ;; Version of the product generation executable that produced the granule.
   PGEVersion
  ])
(record-pretty-printer/enable-record-pretty-printing PGEVersionClassType)

;; The quality statistics element contains measures of quality for the granule. The parameters used
;; to set these measures are not preset and will be determined by the data producer. Each set of
;; measures can occur many times either for the granule as a whole or for individual parameters.
(defrecord QAStatsType
  [
   ;; Granule level % missing data. This attribute can be repeated for individual parameters within
   ;; a granule.
   QAPercentMissingData

   ;; Granule level % out of bounds data. This attribute can be repeated for individual parameters
   ;; within a granule.
   QAPercentOutOfBoundsData

   ;; Granule level % interpolated data. This attribute can be repeated for individual parameters
   ;; within a granule.
   QAPercentInterpolatedData

   ;; This attribute is used to characterize the cloud cover amount of a granule. This attribute may
   ;; be repeated for individual parameters within a granule. (Note - there may be more than one way
   ;; to define a cloud or it's effects within a product containing several parameters; i.e. this
   ;; attribute may be parameter specific).
   QAPercentCloudCover
  ])
(record-pretty-printer/enable-record-pretty-printing QAStatsType)

;; This set of elements describes a file package or a file that contains other files. Normally this
;; is either a tar or a zip file.
(defrecord ArchiveAndDistributionInformationType
  [
   ;; The size of the volume of data contained in the granule. Please use the SizeInBytes element
   ;; either instead of this one or inclusive of this one. The issue with the size element is that
   ;; if CMR data providers use a unit other than Bytes, end users don't know how the granule size
   ;; was calculated. For example, if the unit was MegaBytes, the size could be calculated by using
   ;; 1000xE2 Bytes (MegaBytes) or 1024xE2 Bytes (mebibytes) and therefore there is no systematic
   ;; way to know the actual size of a granule by using the granule metadata record.
   Size

   ;; The unit of the file size.
   SizeUnit

   ;; Allows the provider to provide the checksum value for the file.
   Checksum

   ;; Allows the provider to state whether the distributable item's format is its native format or
   ;; another supported format.
   FormatType

   ;; This element defines a single format for a distributable artifact.
   Format

   ;; Allows the provider to add the list of the files that are included in this one.
   Files

   ;; The mime type of the resource.
   MimeType

   ;; The size in Bytes of the volume of data contained in the granule. Bytes are defined as eight
   ;; bits. Please use this element instead of or inclusive with the Size element. The issue with
   ;; the size element is that if CMR data providers use a unit other than Bytes, end users don't
   ;; know how the granule size was calculated. For example, if the unit was MegaBytes, the size
   ;; could be calculated by using 1000xE2 Bytes (MegaBytes) or 1024xE2 Bytes (mebibytes) and
   ;; therefore there is no systematic way to know the actual size of a granule by using the granule
   ;; metadata record.
   SizeInBytes

   ;; This field describes the name of the actual file.
   Name
  ])
(record-pretty-printer/enable-record-pretty-printing ArchiveAndDistributionInformationType)

;; A reference to a collection metadata record's short name and version, or entry title to which
;; this granule metadata record belongs.
(defrecord CollectionReferenceType
  [
   ;; The collection's short name as per the UMM-C.
   ShortName

   ;; The collection's version as per the UMM-C.
   Version

   ;; The collections entry title as per the UMM-C.
   EntryTitle
  ])
(record-pretty-printer/enable-record-pretty-printing CollectionReferenceType)