;; WARNING: This file was generated from umm-s-json-schema.json. Do not manually modify.
(ns cmr.umm-spec.models.umm-service-models
   "Defines UMM-S clojure records."
 (:require [cmr.common.dev.record-pretty-printer :as record-pretty-printer]))

(defrecord UMM-S
  [
   ;; Bounding box corners = lower left (min x, min y), and upper right (max x and max y).
   BBox

   ;; The name of the contact person who maintains the service.
   ContactPerson

   ;; Abstract provides a brief description of the service the metadata represents.
   Abstract

   ;; The title of the service described by the metadata.
   Title

   ;; Supported requests of the service.
   SupportedRequests

   ;; This provides a object to define the set of options for the service.
   ServiceOptions

   ;; This element describes any data/service related URLs that include project home pages,
   ;; services, related data archives/servers, metadata extensions, direct links to online software
   ;; packages, web mapping services, links to images, or other data.
   RelatedUrls

   ;; This element with the description field allows the author to provide information about any
   ;; constraints for accessing the service. This includes any special restrictions, legal
   ;; prerequisites, limitations and/or warnings on obtaining the service. Some words that may be
   ;; used in this element's value include: Public, In-house, Limited, None. The value field is used
   ;; for special ACL rules (Access Control Lists
   ;; (http://en.wikipedia.org/wiki/Access_control_list)). For example it can be used to hide
   ;; metadata when it isn't ready for public consumption.
   AccessConstraints

   ;; This provides the date (day and time) for which the service record was last reviewed.
   ReviewDate

   ;; The fee for obtaining data through the provided service. The fee is entered as a number, in US
   ;; dollars.
   Fees

   ;; This element enables specification of service keywords.
   ServiceKeywords

   ;; The default format for delivery of the service for the specified layer(s).
   Format

   ;; This element enables specification of Earth science keywords.
   ScienceKeywords

   ;; The name of the contact organization whhic maintains the service.
   ContactOrganization

   ;; This element is used to identify which versions of the services are available to accept
   ;; requests.
   AcceptVersions

   ;; The name of the service.
   Name

   ;; This element contains a description of the service.
   Description

   ;; The width of the requested map.
   Width

   ;; This element is used to provide a list of layer names (identifiers) which are available via
   ;; the service.
   Layers

   ;; Specification of the service, e.g. Web Mapping Service.
   Type

   ;; Version of the service, e.g. 1.1.1.
   Version

   ;; This provides the date (day and time) for which the service record was originally created.
   CreationDate

   ;; The height of the requested map.
   Height
  ])
(record-pretty-printer/enable-record-pretty-printing UMM-S)

;; This element enables specification of service keywords.
(defrecord ServiceKeywordType
  [
   Category

   Topic

   Term

   ServiceSpecificName
  ])
(record-pretty-printer/enable-record-pretty-printing ServiceKeywordType)

;; This element describes service options, subset type, supported SRSs, interpolation types,
;; formats, exceptions and whether the service is synchronous or asyncronous.
(defrecord ServiceOptionsType
  [
   ;; The project element describes the list of names of the formats supported by the service.
   SupportedFormats

   ;; This entity represents the default (native) temporal resolution of the variable in units of
   ;; km.
   TemporalResolution

   ;; This entity represents the default (native) spatial resolution of the variable in units of km.
   ;; See the <gml:offsetVector> flag in the DescribeCoverage request for that coverage.
   NativeResolution

   ;; Resolution of the x dimension of the requested coverage or map. (Use ResX and ResY or Width
   ;; and Height - but not both in the same request).
   ResX

   ;; This field describes the list of exceptions for the service.
   Exceptions

   ;; This element is used to identify the list of supported subsetting requests.
   SubsetType

   ;; This element is used to identify the list of supported Spatial Reference Systems (SRS).
   SupportedSRS

   ;; Resolution of the y dimension of the requested coverage or map. (Use ResX and ResY or Width
   ;; and Height - but not both in the same request).
   ResY

   ;; This element is used to identify the list of supported interpolation types. These are used in
   ;; regridding.
   InterpolationType

   ;; This provides a field to state whether the service is deemed either synchronous or
   ;; asynchronous.
   Synchronous
  ])
(record-pretty-printer/enable-record-pretty-printing ServiceOptionsType)