;; WARNING: This file was generated from umm-var-json-schema.json. Do not manually modify.
(ns cmr.umm-spec.models.umm-variable-models
   "Defines UMM-Var clojure records."
 (:require [cmr.common.dev.record-pretty-printer :as record-pretty-printer]))

(defrecord UMM-Var
  [
   ;; Valid ranges of variable data values.
   ValidRanges

   ;; A variable consists of one or more dimensions. An example of a dimension name is 'XDim'. An
   ;; example of a dimension size is '1200'. Variables are rarely one dimensional.
   Dimensions

   ;; The factor by which the cell value has been multiplied. The cell value is the value given to a
   ;; specific location within an array of data values. An example of a scale factor is '0.002'
   Scale

   ;; The factor to which the cell value has been added. The cell value is the value given to a
   ;; specific location within an array of data values. An example of an offset is '0.49'.
   Offset

   ;; The set information of a variable. The variable is grouped within a set. The set is defined by
   ;; the name, type, size and index. For example, Name: 'Data_Fields', Type: 'General', Size: '15',
   ;; Index: '7' for the case of the variable named 'LST_Day_1km'.
   Sets

   ;; The units associated with a variable.
   Units

   ;; The fill value of the variable in the data file. It is generally a value which falls outside
   ;; the valid range. For example, if the valid range is '0, 360', the fill value may be '-1'. The
   ;; fill value type is data provider-defined. For example, 'Out of Valid Range'.
   FillValues

   ;; The definition of the variable.
   Definition

   ;; The measurement information of a variable.
   Measurements

   ;; The characteristics of a variable. The elements of this section apply to a Variable.
   Characteristics

   ;; Controlled Science Keywords describing the measurements/variables. The controlled vocabulary
   ;; for Science Keywords is maintained in the Keyword Management System (KMS).
   ScienceKeywords

   ;; The name of a variable.
   Name

   ;; Specify basic type of a variable. These types can be either: Science, Ancillary, Quality etc.
   VariableType

   ;; The expanded or long name related to the variable Name.
   LongName

   ;; Specify data type of a variable. These types can be either: uint8, uint16, etc.
   DataType
  ])
(record-pretty-printer/enable-record-pretty-printing UMM-Var)

;; The elements of this section apply to a variable.
(defrecord CharacteristicsType
  [
   ;; Describes the spatial bounds of a variable. Western Longitude, Northern Latitude and Eastern
   ;; Longitude, Southern Latitude - often specified in decimal degrees. For example,
   ;; 'UpperLeftPointMtrs = -180.0, 89.5; LowerRightMtrs = 177.5, -89.5.'
   Bounds

   ;; The computed byte size for the variable, per the data field. Typically, this is the X
   ;; dimension times the Y dimension times the number of bytes in the data type (8, 16, 32, etc.).
   ;; For example, 1200 x 1200 x 16 = 23,040,000.
   Size

   ;; The full path to the variable within the Granule. For example,
   ;; '/<filename>/MODIS_Grid_Daily_1km_LST/Data_Fields/', where filename =
   ;; 'MOD11A1.A2009172.h16v05.006.2016014073638.hdf'.
   Structure

   ;; The measurement conditions of the variable. For example, 'Sampled Particle Size Range: 90 -
   ;; 600 nm'.
   MeasurementConditions

   ;; A text description of the variable’s coordinate range as given by the data provider. For
   ;; example, '90N, 90S, 180E, 180W'.
   Coordinates

   ;; Describes the chunk size of a variable. For example, '100'.
   ChunkSize

   ;; A text description of the variable's mapping projection standard for the variable. For
   ;; example: 'WGS84 Web Mercator'.
   GridMapping

   ;; The reporting conditions of the variable. The conditions over which the measurement of the
   ;; variable are valid. For example, 'STP: 1013 mb and 273 K'.
   ReportingConditions

   ;; The computed byte size units for the variable, per the data field. For example B, KB, MB, GB.
   SizeUnits

   ;; The CF-compliant 'Standard Name' for the variable.
   StandardName

   ;; Provides a link to variable's reference documentation.
   Reference
  ])
(record-pretty-printer/enable-record-pretty-printing CharacteristicsType)

;; The elements of this section apply to a measurement.
(defrecord MeasurementsType
  [
   ;; This element allows authors to provide community sourced words or phrases to further describe
   ;; the variable data.
   MeasurementName

   ;; This element allows authors to identify the source of the measurements.
   MeasurementSource
  ])
(record-pretty-printer/enable-record-pretty-printing MeasurementsType)

;; The elements of this section apply to the fill value of a variable.
(defrecord FillValueType
  [
   ;; The fill value of the variable in the data file.
   Value

   ;; Type of the fill value of the variable in the data file.
   Type

   ;; Description of the fill value of the variable in the data file.
   Description
  ])
(record-pretty-printer/enable-record-pretty-printing FillValueType)

;; The elements of this section apply to variable sets.
(defrecord SetType
  [
   ;; This element enables specification of set name. For example, 'Data_Fields'.
   Name

   ;; This element enables specification of set type. For example, if the variables have been
   ;; grouped together based on a particular theme, such as wavelength, then the type should be set
   ;; to that theme, otherwise it should be set to 'General'.
   Type

   ;; This element specifies the number of variables in the set. For example, if the number of
   ;; variables in the set is fifteen, the size should be set to '15'.
   Size

   ;; This element specifies the index value within the set for this variable, For example, if this
   ;; varible is the third variable in the set, the index value should be set to '3'.
   Index
  ])
(record-pretty-printer/enable-record-pretty-printing SetType)

;; Valid range data value of a variable: minimum and maximum values. For example, '-100, 5000'.
(defrecord ValidRangeType
  [
   ;; Minimum data value of a variable. For example, '-100'.
   Min

   ;; Maximum data value of a variable. For example, '5000'.
   Max
  ])
(record-pretty-printer/enable-record-pretty-printing ValidRangeType)

;; A variable consists of one or more dimensions. An example of a dimension name is 'XDim'. An
;; example of a dimension size is '1200'. Variables are rarely one dimensional.
(defrecord DimensionType
  [
   ;; The name of the dimension of the variable represented in the data field. For example, 'XDim.
   Name

   ;; The size of the dimension of the variable represented in the data field. For example, '1200'.
   Size
  ])
(record-pretty-printer/enable-record-pretty-printing DimensionType)