#!/bin/bash

GRANULES=\
"<Granule>
    <GranuleUR>SS_00107_STD_F0373-L1</GranuleUR>
    <InsertTime>2013-08-27T10:39:14Z</InsertTime>
    <LastUpdate>2013-08-27T10:39:14Z</LastUpdate>
    <Collection>
        <DataSetId>SEASAT_SAR_LEVEL1_GEOTIFF</DataSetId>
    </Collection>
    <DataGranule>
        <SizeMBDataGranule>315.16</SizeMBDataGranule>
        <ProducerGranuleId>SS_00107_STD_F0373</ProducerGranuleId>
        <DayNightFlag>UNSPECIFIED</DayNightFlag>
        <ProductionDateTime>2013-08-27T10:39:14Z</ProductionDateTime>
    </DataGranule>
    <Temporal>
        <RangeDateTime>
            <BeginningDateTime>1978-07-04T12:06:00Z</BeginningDateTime>
            <EndingDateTime>1978-07-04T12:06:15Z</EndingDateTime>
        </RangeDateTime>
    </Temporal>
    <Spatial>
        <HorizontalSpatialDomain>
            <Geometry>
                <GPolygon>
                    <Boundary>
                        <Point>
                            <PointLongitude>-111.6512</PointLongitude>
                            <PointLatitude>19.238</PointLatitude>
                        </Point>
                        <Point>
                            <PointLongitude>-110.6602</PointLongitude>
                            <PointLatitude>19.6319</PointLatitude>
                        </Point>
                        <Point>
                            <PointLongitude>-110.3003</PointLongitude>
                            <PointLatitude>18.7734</PointLatitude>
                        </Point>
                        <Point>
                            <PointLongitude>-111.2851</PointLongitude>
                            <PointLatitude>18.3807</PointLatitude>
                        </Point>
                    </Boundary>
                </GPolygon>
            </Geometry>
        </HorizontalSpatialDomain>
    </Spatial>
    <OrbitCalculatedSpatialDomains>
        <OrbitCalculatedSpatialDomain>
            <OrbitNumber>107</OrbitNumber>
        </OrbitCalculatedSpatialDomain>
    </OrbitCalculatedSpatialDomains>
    <Platforms>
        <Platform>
            <ShortName>SEASAT 1</ShortName>
            <Instruments>
                <Instrument>
                    <ShortName>SAR</ShortName>
                    <Sensors>
                        <Sensor>
                            <ShortName>STD</ShortName>
                        </Sensor>
                    </Sensors>
                </Instrument>
            </Instruments>
        </Platform>
    </Platforms>
    <AdditionalAttributes>
        <AdditionalAttribute>
            <Name>FLIGHT_LINE</Name>
            <Values>
                <Value>NULL</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>OFF_NADIR_ANGLE</Name>
            <Values>
                <Value>-1</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>MD5SUM</Name>
            <Values>
                <Value>185f7979566f5aeae065b7031bc8a122</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>GRANULE_TYPE</Name>
            <Values>
                <Value>SEASAT_STD_FRAME</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>ASCENDING_DESCENDING</Name>
            <Values>
                <Value>ASCENDING</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>FAR_END_LAT</Name>
            <Values>
                <Value>19.6319</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>INSAR_STACK_SIZE</Name>
            <Values>
                <Value>0</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>BEAM_MODE_TYPE</Name>
            <Values>
                <Value>STD</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>INSAR_BASELINE</Name>
            <Values>
                <Value>0</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>CENTER_FRAME_ID</Name>
            <Values>
                <Value>380</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>CENTER_ESA_FRAME</Name>
            <Values>
                <Value>380</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>ACQUISITION_DATE</Name>
            <Values>
                <Value>1978-07-04T12:06:15Z</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>MISSION_NAME</Name>
            <Values>
                <Value>NULL</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>CENTER_LON</Name>
            <Values>
                <Value>-110.9745</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>NEAR_START_LAT</Name>
            <Values>
                <Value>18.3807</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>BEAM_MODE</Name>
            <Values>
                <Value>Standard</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>BEAM_MODE_DESC</Name>
            <Values>
                <Value>ERS-1,ERS-2,JERS-1,SEASAT,SMAP Standard Beam SAR</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>PROCESSING_TYPE</Name>
            <Values>
                <Value>L1</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>PROCESSING_DESCRIPTION</Name>
            <Values>
                <Value>Fully processed SAR data.</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>FRAME_NUMBER</Name>
            <Values>
                <Value>0373</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>PROCESSING_LEVEL</Name>
            <Values>
                <Value>L1</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>PROCESSING_DATE</Name>
            <Values>
                <Value>2013-08-27 10:39:14.517669</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>NEAR_START_LON</Name>
            <Values>
                <Value>-111.2851</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>DOPPLER</Name>
            <Values>
                <Value>-1</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>FAR_START_LAT</Name>
            <Values>
                <Value>18.7734</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>NEAR_END_LON</Name>
            <Values>
                <Value>-111.6512</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>PROCESSING_TYPE_DISPLAY</Name>
            <Values>
                <Value>Level One HDF5 Image</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>POLARIZATION</Name>
            <Values>
                <Value>HH</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>FAR_START_LON</Name>
            <Values>
                <Value>-110.3003</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>THUMBNAIL_URL</Name>
            <Values>
                <Value>https://datapool.asf.alaska.edu/THUMBNAIL/SS/SS_00107_STD_F0373_THUMBNAIL.jpg</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>ASF_PLATFORM</Name>
            <Values>
                <Value>SEASAT</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>INSAR_STACK_ID</Name>
            <Values>
                <Value>0</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>LOOK_DIRECTION</Name>
            <Values>
                <Value>R</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>PATH_NUMBER</Name>
            <Values>
                <Value>106</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>NEAR_END_LAT</Name>
            <Values>
                <Value>19.238</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>FARADAY_ROTATION</Name>
            <Values>
                <Value>NA</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>FAR_END_LON</Name>
            <Values>
                <Value>-110.6602</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>BYTES</Name>
            <Values>
                <Value>330477303</Value>
            </Values>
        </AdditionalAttribute>
        <AdditionalAttribute>
            <Name>CENTER_LAT</Name>
            <Values>
                <Value>19.0068</Value>
            </Values>
        </AdditionalAttribute>
    </AdditionalAttributes>
    <OnlineAccessURLs>
        <OnlineAccessURL>
            <URL>https://datapool.asf.alaska.edu/L1/SS/SS_00107_STD_F0373_h5.zip</URL>
        </OnlineAccessURL>
    </OnlineAccessURLs>
    <Orderable>true</Orderable>
    <Visible>true</Visible>
    <AssociatedBrowseImageUrls>
        <ProviderBrowseUrl>
            <URL>https://datapool.asf.alaska.edu/BROWSE/SS/SS_00107_STD_F0373_BROWSE.jpg</URL>
        </ProviderBrowseUrl>
    </AssociatedBrowseImageUrls>
</Granule>"
