services:
  redis:
    container_name: cmr-redis
    image: docker.io/redis:7-bullseye
    attach: false
    ports:
      - 6379:6379
  elasticsearch:
    container_name: cmr-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
    attach: false
    ports: 
      - 9210:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - indices.breaker.total.use_real_memory=false
      - node.name=embedded-elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9210/_cat/health?v&pretty"]
      interval: 30s
      timeout: 3m
      retries: 6
      start_period: 40s
  kibana:
    container_name: cmr-kibana
    attach: false
    image: docker.elastic.co/kibana/kibana:7.17.14
    depends_on: 
      - elasticsearch
    ports:
      - 5601:5601
  sqs:
    container_name: elastic-sqs
    attach: false
    image: softwaremill/elasticmq-native:1.6.8
    ports:
      - 9324:9324
      - 9325:9325
  cmr:
    container_name: cmr
    image: clojure:temurin-17-lein-bullseye
    depends_on:
    - elasticsearch
    - redis
    - kibana
    - sqs
    working_dir: /cmr/dev-system
    environment:
      - CMR_DEV_SYSTEM_ELASTIC_TYPE=external
      - CMR_DEV_SYSTEM_REDIS_TYPE=external
      - CMR_DEV_SYSTEM_KIBANA_TYPE=external
      - CMR_DEV_SYSTEM_DB_TYPE=external
      - CMR_DEV_SYSTEM_SQS_SERVER_TYPE=external
    ports:
      - 3011:3011
      - 3006:3006
      - 3004:3004
      - 3002:3002
      - 3001:3001
      - 3003:3003
      - 3009:3009
    volumes:
      - ./:/cmr
      - ~/.m2:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock

