# frozen_string_literal: true

source 'https://rubygems.org'

group :test do
  gem 'cucumber', '~> 9.2.1'
  gem 'httparty'
  gem 'jsonpath'
  gem 'nokogiri', "= 1.18.9"
  gem 'rspec'
  gem 'ffi', '~> 1.16.3'
end
