-- This is some sample DDL that would create the tables form Catalog REST..
CREATE TABLE "DEV_52_CATALOG_REST"."PROVIDERS"
( "ID" NUMBER(38,0) NOT NULL ENABLE,
  "CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE,
  "UPDATED_AT" TIMESTAMP (6) NOT NULL ENABLE,
  "PROVIDER_ID" VARCHAR2(255 CHAR),
  "DATASET_ACL_HASH" VARCHAR2(255 CHAR) DEFAULT '',
  "REST_ONLY" NUMBER(1,0) DEFAULT 0,
  PRIMARY KEY ("ID")
)

CREATE TABLE "DEV_52_CATALOG_REST"."FIX_PROV1_DATASET_RECORDS"
( "ID" NUMBER(38,0) NOT NULL ENABLE,
  "ECHO_COLLECTION_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
  "DATASET_ID" VARCHAR2(1030 CHAR) NOT NULL ENABLE,
  "COMPRESSED_XML" BLOB NOT NULL ENABLE,
  "ATOM_XML" CLOB,
  "ATOM_JSON" CLOB,
  "INDEXED_AT" TIMESTAMP (6) DEFAULT TO_TIMESTAMP('1970-01-02 00:00:00:000000','YYYY-MM-DD HH24:MI:SS:FF6'),
  "INDEXED_AT2" TIMESTAMP (6) DEFAULT TO_TIMESTAMP('1970-01-02 00:00:00:000000','YYYY-MM-DD HH24:MI:SS:FF6'),
  "INGEST_UPDATED_AT" TIMESTAMP (6) NOT NULL ENABLE,
  "SHORT_NAME" VARCHAR2(85 CHAR) NOT NULL ENABLE,
  "VERSION_ID" VARCHAR2(80 CHAR) NOT NULL ENABLE,
  "LONG_NAME" VARCHAR2(1024 CHAR) NOT NULL ENABLE,
  "XML_MIME_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE,
  "UPDATED_AT" TIMESTAMP (6),
  "CREATED_AT" TIMESTAMP (6),
  "BEGIN_DATE_TIME" TIMESTAMP (6),
  "END_DATE_TIME" TIMESTAMP (6),
  "DELETE_TIME" TIMESTAMP (6),
  PRIMARY KEY ("ID")
)


CREATE TABLE "DEV_52_CATALOG_REST"."FIX_PROV1_GRANULE_RECORDS"
( "ID" NUMBER(38,0) NOT NULL ENABLE,
  "ECHO_GRANULE_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
  "GRANULE_UR" VARCHAR2(250 CHAR) NOT NULL ENABLE,
  "COMPRESSED_XML" BLOB NOT NULL ENABLE,
  "DATASET_RECORD_ID" NUMBER(38,0) NOT NULL ENABLE,
  "XML_MIME_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE,
  "INDEXED_AT" TIMESTAMP (6) DEFAULT TO_TIMESTAMP('1970-01-02 00:00:00:000000','YYYY-MM-DD HH24:MI:SS:FF6'),
  "INDEXED_AT2" TIMESTAMP (6) DEFAULT TO_TIMESTAMP('1970-01-02 00:00:00:000000','YYYY-MM-DD HH24:MI:SS:FF6'),
  "INGEST_UPDATED_AT" TIMESTAMP (6) NOT NULL ENABLE,
  "UPDATED_AT" TIMESTAMP (6),
  "CREATED_AT" TIMESTAMP (6),
  "BEGIN_DATE_TIME" TIMESTAMP (6),
  "END_DATE_TIME" TIMESTAMP (6),
  "DELETE_TIME" TIMESTAMP (6),
  PRIMARY KEY ("ID")
)