FROM python:3.13-slim

WORKDIR /app

ENV PYTHONPATH=src
ENV AWS_REGION=us-east-1

# Stop Python from buffering stdout/stderr (crucial for live Bamboo logs)
ENV PYTHONUNBUFFERED=1

# Copy package list first to optimize Docker build caching
#COPY requirements.txt .
# Copy the rest of your application code and tests into the container
COPY . .

# Upgrade pip first to avoid Python 3.13 version discovery errors
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Emulate your script's test execution command on container startup
CMD ["python", "-m", "unittest", "discover", "-v", "-s", "./test", "-p", "*_test.py"]

