#!/usr/bin/env python3
"""
Reindexer integration test against a live local CMR backed by Oracle.

Ingests a collection and granules, reindexes the collection, and checks the job
completes with every granule dispatched and still searchable.

Needs running: the CMR dev-system (ingest, search, metadata-db) on Oracle, ES on
9210/9211, ElasticMQ with the indexer queue (scripts/create_queues.sh), DynamoDB Local
with the job table, and the reindexer (DB_BACKEND=oracle, INDEXER_QUEUE_URL,
DYNAMODB_ENDPOINT_URL). Set REINDEXER_URL if it isn't on localhost:8001/reindexer.

    PYTHONPATH=. python3 tests/integration_test.py
"""
import json
import os
import sys
import time
import xml.etree.ElementTree as ET

import httpx

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

INGEST_URL       = os.environ.get("CMR_INGEST_URL",      "http://localhost:3002")
SEARCH_URL       = os.environ.get("CMR_SEARCH_URL",      "http://localhost:3003")
METADATA_DB_URL  = os.environ.get("CMR_METADATA_DB_URL", "http://localhost:3001")
REINDEXER_URL    = os.environ.get("REINDEXER_URL",       "http://localhost:8001/reindexer")
TOKEN            = os.environ.get("CMR_TOKEN",            "mock-echo-system-token")

PROVIDER_ID  = "RXIDXTEST"
NUM_GRANULES = 15

_INGEST_HEADERS = {
    "Authorization": TOKEN,
    "User-Id": "integration-test",
}

UMM_C_CONTENT_TYPE  = "application/vnd.nasa.cmr.umm+json;version=1.18.5"
ECHO10_CONTENT_TYPE = "application/echo10+xml"
ENTRY_TITLE         = "Reindexer Integration Test Collection"

# ---------------------------------------------------------------------------
# Minimal metadata builders
# ---------------------------------------------------------------------------

_COLLECTION_BODY = json.dumps({
    "ShortName": "REINDEX_INT_TEST",
    "Version": "1",
    "EntryTitle": ENTRY_TITLE,
    "Abstract": "Auto-generated by reindexer integration test.",
    "CollectionProgress": "ACTIVE",
    "ProcessingLevel": {"Id": "1"},
    "DOI": {"MissingReason": "Not Applicable"},
    "MetadataSpecification": {
        "URL": "https://cdn.earthdata.nasa.gov/umm/collection/v1.18.5",
        "Name": "UMM-C",
        "Version": "1.18.5",
    },
    "SpatialExtent": {
        "SpatialCoverageType": "HORIZONTAL",
        "HorizontalSpatialDomain": {
            "Geometry": {
                "CoordinateSystem": "CARTESIAN",
                "BoundingRectangles": [
                    {"WestBoundingCoordinate": -180, "EastBoundingCoordinate": 180,
                     "NorthBoundingCoordinate": 90, "SouthBoundingCoordinate": -90},
                ],
            }
        },
        "GranuleSpatialRepresentation": "NO_SPATIAL",
    },
    "TemporalExtents": [
        {"RangeDateTimes": [{"BeginningDateTime": "2020-01-01T00:00:00Z"}]},
    ],
    "Platforms": [
        {"Type": "Not provided", "ShortName": "Not provided",
         "Instruments": [{"ShortName": "Not provided"}]},
    ],
    "ScienceKeywords": [
        {"Category": "EARTH SCIENCE", "Topic": "NOT PROVIDED", "Term": "NOT PROVIDED"},
    ],
    "DataCenters": [
        {"Roles": ["ARCHIVER"], "ShortName": PROVIDER_ID},
    ],
})


def _echo10_granule(granule_ur: str) -> bytes:
    return f"""<Granule>
  <GranuleUR>{granule_ur}</GranuleUR>
  <InsertTime>2021-01-01T00:00:00Z</InsertTime>
  <LastUpdate>2021-01-01T00:00:00Z</LastUpdate>
  <Collection><DataSetId>{ENTRY_TITLE}</DataSetId></Collection>
  <Orderable>false</Orderable>
  <Visible>true</Visible>
</Granule>""".encode()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _concept_id_from_response(r: httpx.Response) -> str:
    """Extract concept-id from CMR ingest response (XML or JSON)."""
    ct = r.headers.get("Content-Type", "")
    if "json" in ct:
        return r.json()["concept-id"]
    root = ET.fromstring(r.text)
    return root.findtext("concept-id") or ""


def _check(label: str, url: str) -> bool:
    try:
        r = httpx.get(url, timeout=5.0)
        # Any response counts as reachable; CMR /health can return 503 for a degraded dependency.
        reachable = r.status_code < 600
        print(f"  {'OK' if reachable else 'FAIL':4s}  {label}  ({r.status_code})")
        return reachable
    except Exception as exc:
        print(f"  FAIL  {label}  ({exc})")
        return False


def _granule_hits(collection_id: str) -> int:
    r = httpx.get(
        f"{SEARCH_URL}/granules.json",
        params={"collection-concept-id": collection_id, "page_size": 0},
        headers={"Authorization": TOKEN},
        timeout=10.0,
    )
    return int(r.headers.get("CMR-Hits", 0))


def _wait_for_hits(collection_id: str, expected: int, timeout: int = 30) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        hits = _granule_hits(collection_id)
        print(f"    ES granule hits: {hits}/{expected}")
        if hits >= expected:
            return True
        time.sleep(2)
    return False


# ---------------------------------------------------------------------------
# Test steps
# ---------------------------------------------------------------------------

def step_check_services() -> bool:
    print("\n[1] Checking services")
    ok  = _check("metadata-db  :3001", f"{METADATA_DB_URL}/health")
    ok &= _check("ingest        :3002", f"{INGEST_URL}/health")
    ok &= _check("search        :3003", f"{SEARCH_URL}/health")
    ok &= _check("reindexer     :8001", f"{REINDEXER_URL}/health")
    return ok


def step_setup_provider() -> None:
    print(f"\n[2] Creating provider {PROVIDER_ID}")
    r = httpx.post(
        f"{METADATA_DB_URL}/providers",
        json={
            "provider-id": PROVIDER_ID,
            "short-name": PROVIDER_ID,
            "cmr-only": False,
            "small": False,
        },
        headers=_INGEST_HEADERS,
        timeout=10.0,
    )
    if r.status_code not in (200, 201, 409):
        r.raise_for_status()
    print(f"  Provider ready (HTTP {r.status_code})")


def step_ingest_collection() -> str:
    print("\n[3] Ingesting collection")
    r = httpx.put(
        f"{INGEST_URL}/providers/{PROVIDER_ID}/collections/reindex-int-test-coll",
        params={"skip_umm_validation": "true"},
        content=_COLLECTION_BODY.encode(),
        headers={**_INGEST_HEADERS, "Content-Type": UMM_C_CONTENT_TYPE,
                 "Cmr-Validate-Keywords": "false"},
        timeout=30.0,
    )
    r.raise_for_status()
    cid = _concept_id_from_response(r)
    print(f"  Collection concept ID: {cid}")
    return cid


def step_ingest_granules() -> list[str]:
    print(f"\n[4] Ingesting {NUM_GRANULES} granules")
    concept_ids: list[str] = []
    for i in range(NUM_GRANULES):
        native_id = f"reindex-int-test-gran-{i:04d}"
        r = httpx.put(
            f"{INGEST_URL}/providers/{PROVIDER_ID}/granules/{native_id}",
            content=_echo10_granule(native_id),
            headers={**_INGEST_HEADERS, "Content-Type": ECHO10_CONTENT_TYPE},
            timeout=30.0,
        )
        r.raise_for_status()
        gid = _concept_id_from_response(r)
        concept_ids.append(gid)
        print(f"  [{i+1:2d}/{NUM_GRANULES}] {gid}")
    return concept_ids


def step_wait_initial_index(collection_id: str) -> bool:
    print("\n[5] Waiting for initial CMR indexing (up to 30s)")
    ok = _wait_for_hits(collection_id, NUM_GRANULES, timeout=30)
    if not ok:
        print("  ERROR: granules did not appear in ES within timeout")
    return ok


def step_trigger_reindex(collection_id: str) -> str:
    print(f"\n[6] Triggering reindexer for collection {collection_id}")
    r = httpx.post(
        f"{REINDEXER_URL}/reindex/granules/collection/{collection_id}",
        headers={"Authorization": TOKEN},
        timeout=10.0,
    )
    r.raise_for_status()
    request_id = r.json().get("request_id", "?")
    print(f"  request_id: {request_id}")
    return request_id


def step_verify_reindexer(collection_id: str, granule_ids: list[str], request_id: str) -> bool:
    print("\n[7] Waiting for the job to finish and the indexer queue to drain (up to 30s)")
    deadline = time.monotonic() + 30
    job: dict = {}
    while time.monotonic() < deadline:
        job = httpx.get(f"{REINDEXER_URL}/jobs/{request_id}", timeout=5.0).json()
        indexer = httpx.get(f"{REINDEXER_URL}/status", timeout=5.0).json()["indexer_queue"] or {}
        depth = indexer.get("available", -1) + indexer.get("in_flight", 0)
        print(f"  job {job.get('status')}, dispatched {job.get('total_dispatched')}, indexer queue depth {depth}")
        if job.get("status") != "running" and depth == 0:
            break
        time.sleep(2)
    print(f"  Job: {json.dumps(job)}")

    hits = _granule_hits(collection_id)
    print(f"  CMR search hits after reindex: {hits}/{NUM_GRANULES}")

    return job.get("status") == "completed" and job.get("total_dispatched", 0) >= NUM_GRANULES and hits >= NUM_GRANULES

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run() -> int:
    print("=" * 60)
    print("CMR Reindexer Integration Test")
    print("=" * 60)

    if not step_check_services():
        print("\nABORT: one or more services unreachable.")
        return 1

    step_setup_provider()
    collection_id = step_ingest_collection()
    granule_ids   = step_ingest_granules()

    if not step_wait_initial_index(collection_id):
        return 1

    request_id = step_trigger_reindex(collection_id)

    ok = step_verify_reindexer(collection_id, granule_ids, request_id)

    print("\n" + "=" * 60)
    if ok:
        print(f"PASS  —  {NUM_GRANULES} granules visible in ES; job completed with all granules dispatched.")
    else:
        print("FAIL  —  see output above.")
    print("=" * 60)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(run())
