services:
  redis:
    container_name: cmr-redis
    image: docker.io/redis:7-bullseye
    ports:
      - 6379:6379
    networks:
      - redis-network
  elasticsearch:
    container_name: cmr-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
    ports: 
      - 9210:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - indices.breaker.total.use_real_memory=false
      - node.name=embedded-elastic
    networks:
      elasticsearch-network:
        aliases:
          - elasticsearch
networks:
  elasticsearch-network: {}
  redis-network: {}
