services:
  redis:
    container_name: cmr-redis
    image: docker.io/redis:7-bullseye
    ports:
      - 6379:6379
    networks:
      - redis-network
  elasticsearch:
    container_name: cmr-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
    ports: 
      - 9210:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - indices.breaker.total.use_real_memory=false
      - node.name=embedded-elastic
    networks:
      elasticsearch-network:
        aliases:
          - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9210/_cat/health?v&pretty"]
      interval: 30s
      timeout: 3m
      retries: 6
      start_period: 40s
  kibana:
    container_name: cmr-kibana
    depends_on: 
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.17.14
    ports:
      - 5601:5601
    networks:
      - elasticsearch-network

networks:
  elasticsearch-network: {}
  redis-network: {}
