services:
  redis:
    container_name: cmr-redis
    image: docker.io/redis:7-bullseye
    ports:
      - 6379:6379
    networks:
      - redis-network
  elasticsearch:
    container_name: cmr-elasticsearch
    build:
      context: .
      dockerfile: resources/elasticsearch/Dockerfile.elasticsearch
    image: cmr-elasticsearch:8.19.14
    ports:
      - 9211:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - indices.id_field_data.enabled=true
      - indices.breaker.total.use_real_memory=false
      - node.name=embedded-elastic
      - ES_JAVA_OPTS=-Xms2g -Xmx2g -Djava.security.policy=/usr/share/elasticsearch/config/embedded-security.policy
    networks:
      elasticsearch-network:
        aliases:
          - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health?v&pretty"]
      interval: 30s
      timeout: 3m
      retries: 6
      start_period: 40s
  gran-elasticsearch:
    container_name: cmr-gran-elasticsearch
    build:
      context: .
      dockerfile: resources/elasticsearch/Dockerfile.elasticsearch
    image: cmr-elasticsearch:8.19.14
    ports:
      - 9210:9200
      - 9301:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - indices.id_field_data.enabled=true
      - indices.breaker.total.use_real_memory=false
      - node.name=gran-embedded-elastic
      - ES_JAVA_OPTS=-Xms2g -Xmx2g -Djava.security.policy=/usr/share/elasticsearch/config/embedded-security.policy
    networks:
      elasticsearch-network:
        aliases:
          - gran-elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health?v&pretty"]
      interval: 30s
      timeout: 3m
      retries: 6
      start_period: 40s
  kibana:
    container_name: cmr-kibana
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.19.14
    ports:
      - 5602:5601
    environment:
      - XPACK_SECURITY_ENABLED=false
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=something_at_least_32_characters_long_123
      - XPACK_REPORTING_ENCRYPTIONKEY=something_at_least_32_characters_long_456
      - XPACK_SECURITY_ENCRYPTIONKEY=something_at_least_32_characters_long_789
    networks:
      - elasticsearch-network
  gran-kibana:
    container_name: cmr-gran-kibana
    depends_on:
      - gran-elasticsearch
    image: docker.elastic.co/kibana/kibana:8.19.14
    ports:
      - 5601:5601
    environment:
      - XPACK_SECURITY_ENABLED=false
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=something_at_least_32_characters_long_123
      - XPACK_REPORTING_ENCRYPTIONKEY=something_at_least_32_characters_long_456
      - XPACK_SECURITY_ENCRYPTIONKEY=something_at_least_32_characters_long_789
    networks:
      - elasticsearch-network

networks:
  elasticsearch-network: {}
  redis-network: {}
