FROM clojure:temurin-17-lein-bullseye

VOLUME /cmr
ENV PATH /cmr/bin:$PATH

WORKDIR /cmr

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install --assume-yes \
      python3 \
      curl \
      netbase \
      unzip \
      zip \
 && rm -rf /var/lib/apt/lists/*

RUN cmr build all

RUN java -jar -Xmx1g cmr-dev-system-0.1.0-SNAPSHOT-standalone.jar