FROM docker.elastic.co/elasticsearch/elasticsearch:8.19.14

COPY plugins /usr/share/elasticsearch/plugins/
COPY embedded-security.policy /usr/share/elasticsearch/config/embedded-security.policy

USER elasticsearch
CMD export "ES_JAVA_OPTS=$ES_JAVA_OPTS -Djava.security.policy=/usr/share/elasticsearch/config/embedded-security.policy" && \
  ./bin/elasticsearch -E "discovery.type=single-node" -E "xpack.security.enabled=false" -E "indices.id_field_data.enabled=true"
