FROM docker.elastic.co/elasticsearch/elasticsearch:8.15.5

COPY plugins /usr/share/elasticsearch/plugins/
COPY embedded-security.policy /usr/share/elasticsearch/config/embedded-security.policy

USER elasticsearch
CMD export "ES_JAVA_OPTS=$ES_JAVA_OPTS -Djava.security.policy=/usr/share/elasticsearch/config/embedded-security.policy" && \
  ./bin/elasticsearch -E "discovery.type=single-node"
